insert into Associe values ('Traditionnel', 1)
insert into Associe values ('Traditionnel', 2)
insert into Associe values ('Traditionnel', 3)
insert into Associe values ('Combiné 5-en-1', 1)
insert into Associe values ('Combiné 5-en-1', 2)
insert into Associe values ('Combiné 5-en-1', 3)
insert into Associe values ('Bas de gamme', 1)
insert into Associe values ('Bas de gamme', 2)
insert into Associe values ('Bas de gamme', 3)
