insert into CombineSP values ('French fries with sausages', 1)
insert into CombineSP values ('Linguine with clams', 1)
insert into CombineSP values ('Teriyaki Chicken donburi', 1)
insert into CombineSP values ('Philadelphia maki', 1)
insert into CombineSP values ('California maki', 1)
insert into CombineSP values ('Mushroom Risotto', 1)
insert into CombineSP values ('Pork sausage roll', 1)
insert into CombineSP values ('Fettuccine Alfredo', 1)
insert into CombineSP values ('Risotto with seafood', 1)
insert into CombineSP values ('Vegetable Soup', 1)
insert into CombineSP values ('Tiramisù', 1)
insert into CombineSP values ('Cheeseburger', 1)
insert into CombineSP values ('Tuna sashimi', 1)
insert into CombineSP values ('Chilli con carne', 1)
insert into CombineSP values ('Pasta and Beans', 1)
insert into CombineSP values ('Fish and chips', 1)
insert into CombineSP values ('Lasagne', 1)
insert into CombineSP values ('Pasta with Tomato and Basil', 1)
insert into CombineSP values ('Souvlaki', 1)
insert into CombineSP values ('Chicken milanese', 1)
insert into CombineSP values ('Salmon nigiri', 1)
insert into CombineSP values ('Caesar Salad', 1)
insert into CombineSP values ('Chicken Fajitas', 1)
insert into CombineSP values ('Pork belly buns', 1)
insert into CombineSP values ('Ricotta stuffed Ravioli', 1)
insert into CombineSP values ('Caprese Salad', 1)
insert into CombineSP values ('Ebiten maki', 1)
insert into CombineSP values ('Barbecue Ribs', 1)
insert into CombineSP values ('Scotch eggs', 1)
insert into CombineSP values ('Katsu Curry', 1)
insert into CombineSP values ('Pasta Carbonara', 1)
insert into CombineSP values ('Bruschette with Tomato', 1)
insert into CombineSP values ('Pappardelle alla Bolognese', 1)
insert into CombineSP values ('Califlower penne', 1)
insert into CombineSP values ('Pizza', 1)
insert into CombineSP values ('Meatballs with sauce', 1)
insert into CombineSP values ('Chicken wings', 1)
insert into CombineSP values ('French fries with sausages', 2)
insert into CombineSP values ('Linguine with clams', 2)
insert into CombineSP values ('Teriyaki Chicken donburi', 2)
insert into CombineSP values ('Philadelphia maki', 2)
insert into CombineSP values ('California maki', 2)
insert into CombineSP values ('Mushroom Risotto', 2)
insert into CombineSP values ('Pork sausage roll', 2)
insert into CombineSP values ('Fettuccine Alfredo', 2)
insert into CombineSP values ('Risotto with seafood', 2)
insert into CombineSP values ('Vegetable Soup', 2)
insert into CombineSP values ('Tiramisù', 2)
insert into CombineSP values ('Cheeseburger', 2)
insert into CombineSP values ('Tuna sashimi', 2)
insert into CombineSP values ('Chilli con carne', 2)
insert into CombineSP values ('Pasta and Beans', 2)
insert into CombineSP values ('Fish and chips', 2)
insert into CombineSP values ('Lasagne', 2)
insert into CombineSP values ('Pasta with Tomato and Basil', 2)
insert into CombineSP values ('Souvlaki', 2)
insert into CombineSP values ('Chicken milanese', 2)
insert into CombineSP values ('Salmon nigiri', 2)
insert into CombineSP values ('Caesar Salad', 2)
insert into CombineSP values ('Chicken Fajitas', 2)
insert into CombineSP values ('Pork belly buns', 2)
insert into CombineSP values ('Ricotta stuffed Ravioli', 2)
insert into CombineSP values ('Caprese Salad', 2)
insert into CombineSP values ('Ebiten maki', 2)
insert into CombineSP values ('Barbecue Ribs', 2)
insert into CombineSP values ('Scotch eggs', 2)
insert into CombineSP values ('Katsu Curry', 2)
insert into CombineSP values ('Pasta Carbonara', 2)
insert into CombineSP values ('Bruschette with Tomato', 2)
insert into CombineSP values ('Pappardelle alla Bolognese', 2)
insert into CombineSP values ('Califlower penne', 2)
insert into CombineSP values ('Pizza', 2)
insert into CombineSP values ('Meatballs with sauce', 2)
insert into CombineSP values ('Chicken wings', 2)
insert into CombineSP values ('French fries with sausages', 3)
insert into CombineSP values ('Linguine with clams', 3)
insert into CombineSP values ('Teriyaki Chicken donburi', 3)
insert into CombineSP values ('Philadelphia maki', 3)
insert into CombineSP values ('California maki', 3)
insert into CombineSP values ('Mushroom Risotto', 3)
insert into CombineSP values ('Pork sausage roll', 3)
insert into CombineSP values ('Fettuccine Alfredo', 3)
insert into CombineSP values ('Risotto with seafood', 3)
insert into CombineSP values ('Vegetable Soup', 3)
insert into CombineSP values ('Tiramisù', 3)
insert into CombineSP values ('Cheeseburger', 3)
insert into CombineSP values ('Tuna sashimi', 3)
insert into CombineSP values ('Chilli con carne', 3)
insert into CombineSP values ('Pasta and Beans', 3)
insert into CombineSP values ('Fish and chips', 3)
insert into CombineSP values ('Lasagne', 3)
insert into CombineSP values ('Pasta with Tomato and Basil', 3)
insert into CombineSP values ('Souvlaki', 3)
insert into CombineSP values ('Chicken milanese', 3)
insert into CombineSP values ('Salmon nigiri', 3)
insert into CombineSP values ('Caesar Salad', 3)
insert into CombineSP values ('Chicken Fajitas', 3)
insert into CombineSP values ('Pork belly buns', 3)
insert into CombineSP values ('Ricotta stuffed Ravioli', 3)
insert into CombineSP values ('Caprese Salad', 3)
insert into CombineSP values ('Ebiten maki', 3)
insert into CombineSP values ('Barbecue Ribs', 3)
insert into CombineSP values ('Scotch eggs', 3)
insert into CombineSP values ('Katsu Curry', 3)
insert into CombineSP values ('Pasta Carbonara', 3)
insert into CombineSP values ('Bruschette with Tomato', 3)
insert into CombineSP values ('Pappardelle alla Bolognese', 3)
insert into CombineSP values ('Califlower penne', 3)
insert into CombineSP values ('Pizza', 3)
insert into CombineSP values ('Meatballs with sauce', 3)
insert into CombineSP values ('Chicken wings', 3)
insert into CombineSP values ('French fries with sausages', 4)
insert into CombineSP values ('Linguine with clams', 4)
insert into CombineSP values ('Teriyaki Chicken donburi', 4)
insert into CombineSP values ('Philadelphia maki', 4)
insert into CombineSP values ('California maki', 4)
insert into CombineSP values ('Mushroom Risotto', 4)
insert into CombineSP values ('Pork sausage roll', 4)
insert into CombineSP values ('Fettuccine Alfredo', 4)
insert into CombineSP values ('Risotto with seafood', 4)
insert into CombineSP values ('Vegetable Soup', 4)
insert into CombineSP values ('Tiramisù', 4)
insert into CombineSP values ('Cheeseburger', 4)
insert into CombineSP values ('Tuna sashimi', 4)
insert into CombineSP values ('Chilli con carne', 4)
insert into CombineSP values ('Pasta and Beans', 4)
insert into CombineSP values ('Fish and chips', 4)
insert into CombineSP values ('Lasagne', 4)
insert into CombineSP values ('Pasta with Tomato and Basil', 4)
insert into CombineSP values ('Souvlaki', 4)
insert into CombineSP values ('Chicken milanese', 4)
insert into CombineSP values ('Salmon nigiri', 4)
insert into CombineSP values ('Caesar Salad', 4)
insert into CombineSP values ('Chicken Fajitas', 4)
insert into CombineSP values ('Pork belly buns', 4)
insert into CombineSP values ('Ricotta stuffed Ravioli', 4)
insert into CombineSP values ('Caprese Salad', 4)
insert into CombineSP values ('Ebiten maki', 4)
insert into CombineSP values ('Barbecue Ribs', 4)
insert into CombineSP values ('Scotch eggs', 4)
insert into CombineSP values ('Katsu Curry', 4)
insert into CombineSP values ('Pasta Carbonara', 4)
insert into CombineSP values ('Bruschette with Tomato', 4)
insert into CombineSP values ('Pappardelle alla Bolognese', 4)
insert into CombineSP values ('Califlower penne', 4)
insert into CombineSP values ('Pizza', 4)
insert into CombineSP values ('Meatballs with sauce', 4)
insert into CombineSP values ('Chicken wings', 4)
insert into CombineSP values ('French fries with sausages', 5)
insert into CombineSP values ('Linguine with clams', 5)
insert into CombineSP values ('Teriyaki Chicken donburi', 5)
insert into CombineSP values ('Philadelphia maki', 5)
insert into CombineSP values ('California maki', 5)
insert into CombineSP values ('Mushroom Risotto', 5)
insert into CombineSP values ('Pork sausage roll', 5)
insert into CombineSP values ('Fettuccine Alfredo', 5)
insert into CombineSP values ('Risotto with seafood', 5)
insert into CombineSP values ('Vegetable Soup', 5)
insert into CombineSP values ('Tiramisù', 5)
insert into CombineSP values ('Cheeseburger', 5)
insert into CombineSP values ('Tuna sashimi', 5)
insert into CombineSP values ('Chilli con carne', 5)
insert into CombineSP values ('Pasta and Beans', 5)
insert into CombineSP values ('Fish and chips', 5)
insert into CombineSP values ('Lasagne', 5)
insert into CombineSP values ('Pasta with Tomato and Basil', 5)
insert into CombineSP values ('Souvlaki', 5)
insert into CombineSP values ('Chicken milanese', 5)
insert into CombineSP values ('Salmon nigiri', 5)
insert into CombineSP values ('Caesar Salad', 5)
insert into CombineSP values ('Chicken Fajitas', 5)
insert into CombineSP values ('Pork belly buns', 5)
insert into CombineSP values ('Ricotta stuffed Ravioli', 5)
insert into CombineSP values ('Caprese Salad', 5)
insert into CombineSP values ('Ebiten maki', 5)
insert into CombineSP values ('Barbecue Ribs', 5)
insert into CombineSP values ('Scotch eggs', 5)
insert into CombineSP values ('Katsu Curry', 5)
insert into CombineSP values ('Pasta Carbonara', 5)
insert into CombineSP values ('Bruschette with Tomato', 5)
insert into CombineSP values ('Pappardelle alla Bolognese', 5)
insert into CombineSP values ('Califlower penne', 5)
insert into CombineSP values ('Pizza', 5)
insert into CombineSP values ('Meatballs with sauce', 5)
insert into CombineSP values ('Chicken wings', 5)
insert into CombineSP values ('French fries with sausages', 6)
insert into CombineSP values ('Linguine with clams', 6)
insert into CombineSP values ('Teriyaki Chicken donburi', 6)
insert into CombineSP values ('Philadelphia maki', 6)
insert into CombineSP values ('California maki', 6)
insert into CombineSP values ('Mushroom Risotto', 6)
insert into CombineSP values ('Pork sausage roll', 6)
insert into CombineSP values ('Fettuccine Alfredo', 6)
insert into CombineSP values ('Risotto with seafood', 6)
insert into CombineSP values ('Vegetable Soup', 6)
insert into CombineSP values ('Tiramisù', 6)
insert into CombineSP values ('Cheeseburger', 6)
insert into CombineSP values ('Tuna sashimi', 6)
insert into CombineSP values ('Chilli con carne', 6)
insert into CombineSP values ('Pasta and Beans', 6)
insert into CombineSP values ('Fish and chips', 6)
insert into CombineSP values ('Lasagne', 6)
insert into CombineSP values ('Pasta with Tomato and Basil', 6)
insert into CombineSP values ('Souvlaki', 6)
insert into CombineSP values ('Chicken milanese', 6)
insert into CombineSP values ('Salmon nigiri', 6)
insert into CombineSP values ('Caesar Salad', 6)
insert into CombineSP values ('Chicken Fajitas', 6)
insert into CombineSP values ('Pork belly buns', 6)
insert into CombineSP values ('Ricotta stuffed Ravioli', 6)
insert into CombineSP values ('Caprese Salad', 6)
insert into CombineSP values ('Ebiten maki', 6)
insert into CombineSP values ('Barbecue Ribs', 6)
insert into CombineSP values ('Scotch eggs', 6)
insert into CombineSP values ('Katsu Curry', 6)
insert into CombineSP values ('Pasta Carbonara', 6)
insert into CombineSP values ('Bruschette with Tomato', 6)
insert into CombineSP values ('Pappardelle alla Bolognese', 6)
insert into CombineSP values ('Califlower penne', 6)
insert into CombineSP values ('Pizza', 6)
insert into CombineSP values ('Meatballs with sauce', 6)
insert into CombineSP values ('Chicken wings', 6)
insert into CombineSP values ('French fries with sausages', 7)
insert into CombineSP values ('Linguine with clams', 7)
insert into CombineSP values ('Teriyaki Chicken donburi', 7)
insert into CombineSP values ('Philadelphia maki', 7)
insert into CombineSP values ('California maki', 7)
insert into CombineSP values ('Mushroom Risotto', 7)
insert into CombineSP values ('Pork sausage roll', 7)
insert into CombineSP values ('Fettuccine Alfredo', 7)
insert into CombineSP values ('Risotto with seafood', 7)
insert into CombineSP values ('Vegetable Soup', 7)
insert into CombineSP values ('Tiramisù', 7)
insert into CombineSP values ('Cheeseburger', 7)
insert into CombineSP values ('Tuna sashimi', 7)
insert into CombineSP values ('Chilli con carne', 7)
insert into CombineSP values ('Pasta and Beans', 7)
insert into CombineSP values ('Fish and chips', 7)
insert into CombineSP values ('Lasagne', 7)
insert into CombineSP values ('Pasta with Tomato and Basil', 7)
insert into CombineSP values ('Souvlaki', 7)
insert into CombineSP values ('Chicken milanese', 7)
insert into CombineSP values ('Salmon nigiri', 7)
insert into CombineSP values ('Caesar Salad', 7)
insert into CombineSP values ('Chicken Fajitas', 7)
insert into CombineSP values ('Pork belly buns', 7)
insert into CombineSP values ('Ricotta stuffed Ravioli', 7)
insert into CombineSP values ('Caprese Salad', 7)
insert into CombineSP values ('Ebiten maki', 7)
insert into CombineSP values ('Barbecue Ribs', 7)
insert into CombineSP values ('Scotch eggs', 7)
insert into CombineSP values ('Katsu Curry', 7)
insert into CombineSP values ('Pasta Carbonara', 7)
insert into CombineSP values ('Bruschette with Tomato', 7)
insert into CombineSP values ('Pappardelle alla Bolognese', 7)
insert into CombineSP values ('Califlower penne', 7)
insert into CombineSP values ('Pizza', 7)
insert into CombineSP values ('Meatballs with sauce', 7)
insert into CombineSP values ('Chicken wings', 7)
insert into CombineSP values ('French fries with sausages', 8)
insert into CombineSP values ('Linguine with clams', 8)
insert into CombineSP values ('Teriyaki Chicken donburi', 8)
insert into CombineSP values ('Philadelphia maki', 8)
insert into CombineSP values ('California maki', 8)
insert into CombineSP values ('Mushroom Risotto', 8)
insert into CombineSP values ('Pork sausage roll', 8)
insert into CombineSP values ('Fettuccine Alfredo', 8)
insert into CombineSP values ('Risotto with seafood', 8)
insert into CombineSP values ('Vegetable Soup', 8)
insert into CombineSP values ('Tiramisù', 8)
insert into CombineSP values ('Cheeseburger', 8)
insert into CombineSP values ('Tuna sashimi', 8)
insert into CombineSP values ('Chilli con carne', 8)
insert into CombineSP values ('Pasta and Beans', 8)
insert into CombineSP values ('Fish and chips', 8)
insert into CombineSP values ('Lasagne', 8)
insert into CombineSP values ('Pasta with Tomato and Basil', 8)
insert into CombineSP values ('Souvlaki', 8)
insert into CombineSP values ('Chicken milanese', 8)
insert into CombineSP values ('Salmon nigiri', 8)
insert into CombineSP values ('Caesar Salad', 8)
insert into CombineSP values ('Chicken Fajitas', 8)
insert into CombineSP values ('Pork belly buns', 8)
insert into CombineSP values ('Ricotta stuffed Ravioli', 8)
insert into CombineSP values ('Caprese Salad', 8)
insert into CombineSP values ('Ebiten maki', 8)
insert into CombineSP values ('Barbecue Ribs', 8)
insert into CombineSP values ('Scotch eggs', 8)
insert into CombineSP values ('Katsu Curry', 8)
insert into CombineSP values ('Pasta Carbonara', 8)
insert into CombineSP values ('Bruschette with Tomato', 8)
insert into CombineSP values ('Pappardelle alla Bolognese', 8)
insert into CombineSP values ('Califlower penne', 8)
insert into CombineSP values ('Pizza', 8)
insert into CombineSP values ('Meatballs with sauce', 8)
insert into CombineSP values ('Chicken wings', 8)
insert into CombineSP values ('French fries with sausages', 9)
insert into CombineSP values ('Linguine with clams', 9)
insert into CombineSP values ('Teriyaki Chicken donburi', 9)
insert into CombineSP values ('Philadelphia maki', 9)
insert into CombineSP values ('California maki', 9)
insert into CombineSP values ('Mushroom Risotto', 9)
insert into CombineSP values ('Pork sausage roll', 9)
insert into CombineSP values ('Fettuccine Alfredo', 9)
insert into CombineSP values ('Risotto with seafood', 9)
insert into CombineSP values ('Vegetable Soup', 9)
insert into CombineSP values ('Tiramisù', 9)
insert into CombineSP values ('Cheeseburger', 9)
insert into CombineSP values ('Tuna sashimi', 9)
insert into CombineSP values ('Chilli con carne', 9)
insert into CombineSP values ('Pasta and Beans', 9)
insert into CombineSP values ('Fish and chips', 9)
insert into CombineSP values ('Lasagne', 9)
insert into CombineSP values ('Pasta with Tomato and Basil', 9)
insert into CombineSP values ('Souvlaki', 9)
insert into CombineSP values ('Chicken milanese', 9)
insert into CombineSP values ('Salmon nigiri', 9)
insert into CombineSP values ('Caesar Salad', 9)
insert into CombineSP values ('Chicken Fajitas', 9)
insert into CombineSP values ('Pork belly buns', 9)
insert into CombineSP values ('Ricotta stuffed Ravioli', 9)
insert into CombineSP values ('Caprese Salad', 9)
insert into CombineSP values ('Ebiten maki', 9)
insert into CombineSP values ('Barbecue Ribs', 9)
insert into CombineSP values ('Scotch eggs', 9)
insert into CombineSP values ('Katsu Curry', 9)
insert into CombineSP values ('Pasta Carbonara', 9)
insert into CombineSP values ('Bruschette with Tomato', 9)
insert into CombineSP values ('Pappardelle alla Bolognese', 9)
insert into CombineSP values ('Califlower penne', 9)
insert into CombineSP values ('Pizza', 9)
insert into CombineSP values ('Meatballs with sauce', 9)
insert into CombineSP values ('Chicken wings', 9)
insert into CombineSP values ('French fries with sausages', 10)
insert into CombineSP values ('Linguine with clams', 10)
insert into CombineSP values ('Teriyaki Chicken donburi', 10)
insert into CombineSP values ('Philadelphia maki', 10)
insert into CombineSP values ('California maki', 10)
insert into CombineSP values ('Mushroom Risotto', 10)
insert into CombineSP values ('Pork sausage roll', 10)
insert into CombineSP values ('Fettuccine Alfredo', 10)
insert into CombineSP values ('Risotto with seafood', 10)
insert into CombineSP values ('Vegetable Soup', 10)
insert into CombineSP values ('Tiramisù', 10)
insert into CombineSP values ('Cheeseburger', 10)
insert into CombineSP values ('Tuna sashimi', 10)
insert into CombineSP values ('Chilli con carne', 10)
insert into CombineSP values ('Pasta and Beans', 10)
insert into CombineSP values ('Fish and chips', 10)
insert into CombineSP values ('Lasagne', 10)
insert into CombineSP values ('Pasta with Tomato and Basil', 10)
insert into CombineSP values ('Souvlaki', 10)
insert into CombineSP values ('Chicken milanese', 10)
insert into CombineSP values ('Salmon nigiri', 10)
insert into CombineSP values ('Caesar Salad', 10)
insert into CombineSP values ('Chicken Fajitas', 10)
insert into CombineSP values ('Pork belly buns', 10)
insert into CombineSP values ('Ricotta stuffed Ravioli', 10)
insert into CombineSP values ('Caprese Salad', 10)
insert into CombineSP values ('Ebiten maki', 10)
insert into CombineSP values ('Barbecue Ribs', 10)
insert into CombineSP values ('Scotch eggs', 10)
insert into CombineSP values ('Katsu Curry', 10)
insert into CombineSP values ('Pasta Carbonara', 10)
insert into CombineSP values ('Bruschette with Tomato', 10)
insert into CombineSP values ('Pappardelle alla Bolognese', 10)
insert into CombineSP values ('Califlower penne', 10)
insert into CombineSP values ('Pizza', 10)
insert into CombineSP values ('Meatballs with sauce', 10)
insert into CombineSP values ('Chicken wings', 10)
insert into CombineSP values ('French fries with sausages', 11)
insert into CombineSP values ('Linguine with clams', 11)
insert into CombineSP values ('Teriyaki Chicken donburi', 11)
insert into CombineSP values ('Philadelphia maki', 11)
insert into CombineSP values ('California maki', 11)
insert into CombineSP values ('Mushroom Risotto', 11)
insert into CombineSP values ('Pork sausage roll', 11)
insert into CombineSP values ('Fettuccine Alfredo', 11)
insert into CombineSP values ('Risotto with seafood', 11)
insert into CombineSP values ('Vegetable Soup', 11)
insert into CombineSP values ('Tiramisù', 11)
insert into CombineSP values ('Cheeseburger', 11)
insert into CombineSP values ('Tuna sashimi', 11)
insert into CombineSP values ('Chilli con carne', 11)
insert into CombineSP values ('Pasta and Beans', 11)
insert into CombineSP values ('Fish and chips', 11)
insert into CombineSP values ('Lasagne', 11)
insert into CombineSP values ('Pasta with Tomato and Basil', 11)
insert into CombineSP values ('Souvlaki', 11)
insert into CombineSP values ('Chicken milanese', 11)
insert into CombineSP values ('Salmon nigiri', 11)
insert into CombineSP values ('Caesar Salad', 11)
insert into CombineSP values ('Chicken Fajitas', 11)
insert into CombineSP values ('Pork belly buns', 11)
insert into CombineSP values ('Ricotta stuffed Ravioli', 11)
insert into CombineSP values ('Caprese Salad', 11)
insert into CombineSP values ('Ebiten maki', 11)
insert into CombineSP values ('Barbecue Ribs', 11)
insert into CombineSP values ('Scotch eggs', 11)
insert into CombineSP values ('Katsu Curry', 11)
insert into CombineSP values ('Pasta Carbonara', 11)
insert into CombineSP values ('Bruschette with Tomato', 11)
insert into CombineSP values ('Pappardelle alla Bolognese', 11)
insert into CombineSP values ('Califlower penne', 11)
insert into CombineSP values ('Pizza', 11)
insert into CombineSP values ('Meatballs with sauce', 11)
insert into CombineSP values ('Chicken wings', 11)
insert into CombineSP values ('French fries with sausages', 12)
insert into CombineSP values ('Linguine with clams', 12)
insert into CombineSP values ('Teriyaki Chicken donburi', 12)
insert into CombineSP values ('Philadelphia maki', 12)
insert into CombineSP values ('California maki', 12)
insert into CombineSP values ('Mushroom Risotto', 12)
insert into CombineSP values ('Pork sausage roll', 12)
insert into CombineSP values ('Fettuccine Alfredo', 12)
insert into CombineSP values ('Risotto with seafood', 12)
insert into CombineSP values ('Vegetable Soup', 12)
insert into CombineSP values ('Tiramisù', 12)
insert into CombineSP values ('Cheeseburger', 12)
insert into CombineSP values ('Tuna sashimi', 12)
insert into CombineSP values ('Chilli con carne', 12)
insert into CombineSP values ('Pasta and Beans', 12)
insert into CombineSP values ('Fish and chips', 12)
insert into CombineSP values ('Lasagne', 12)
insert into CombineSP values ('Pasta with Tomato and Basil', 12)
insert into CombineSP values ('Souvlaki', 12)
insert into CombineSP values ('Chicken milanese', 12)
insert into CombineSP values ('Salmon nigiri', 12)
insert into CombineSP values ('Caesar Salad', 12)
insert into CombineSP values ('Chicken Fajitas', 12)
insert into CombineSP values ('Pork belly buns', 12)
insert into CombineSP values ('Ricotta stuffed Ravioli', 12)
insert into CombineSP values ('Caprese Salad', 12)
insert into CombineSP values ('Ebiten maki', 12)
insert into CombineSP values ('Barbecue Ribs', 12)
insert into CombineSP values ('Scotch eggs', 12)
insert into CombineSP values ('Katsu Curry', 12)
insert into CombineSP values ('Pasta Carbonara', 12)
insert into CombineSP values ('Bruschette with Tomato', 12)
insert into CombineSP values ('Pappardelle alla Bolognese', 12)
insert into CombineSP values ('Califlower penne', 12)
insert into CombineSP values ('Pizza', 12)
insert into CombineSP values ('Meatballs with sauce', 12)
insert into CombineSP values ('Chicken wings', 12)
insert into CombineSP values ('French fries with sausages', 13)
insert into CombineSP values ('Linguine with clams', 13)
insert into CombineSP values ('Teriyaki Chicken donburi', 13)
insert into CombineSP values ('Philadelphia maki', 13)
insert into CombineSP values ('California maki', 13)
insert into CombineSP values ('Mushroom Risotto', 13)
insert into CombineSP values ('Pork sausage roll', 13)
insert into CombineSP values ('Fettuccine Alfredo', 13)
insert into CombineSP values ('Risotto with seafood', 13)
insert into CombineSP values ('Vegetable Soup', 13)
insert into CombineSP values ('Tiramisù', 13)
insert into CombineSP values ('Cheeseburger', 13)
insert into CombineSP values ('Tuna sashimi', 13)
insert into CombineSP values ('Chilli con carne', 13)
insert into CombineSP values ('Pasta and Beans', 13)
insert into CombineSP values ('Fish and chips', 13)
insert into CombineSP values ('Lasagne', 13)
insert into CombineSP values ('Pasta with Tomato and Basil', 13)
insert into CombineSP values ('Souvlaki', 13)
insert into CombineSP values ('Chicken milanese', 13)
insert into CombineSP values ('Salmon nigiri', 13)
insert into CombineSP values ('Caesar Salad', 13)
insert into CombineSP values ('Chicken Fajitas', 13)
insert into CombineSP values ('Pork belly buns', 13)
insert into CombineSP values ('Ricotta stuffed Ravioli', 13)
insert into CombineSP values ('Caprese Salad', 13)
insert into CombineSP values ('Ebiten maki', 13)
insert into CombineSP values ('Barbecue Ribs', 13)
insert into CombineSP values ('Scotch eggs', 13)
insert into CombineSP values ('Katsu Curry', 13)
insert into CombineSP values ('Pasta Carbonara', 13)
insert into CombineSP values ('Bruschette with Tomato', 13)
insert into CombineSP values ('Pappardelle alla Bolognese', 13)
insert into CombineSP values ('Califlower penne', 13)
insert into CombineSP values ('Pizza', 13)
insert into CombineSP values ('Meatballs with sauce', 13)
insert into CombineSP values ('Chicken wings', 13)
insert into CombineSP values ('French fries with sausages', 14)
insert into CombineSP values ('Linguine with clams', 14)
insert into CombineSP values ('Teriyaki Chicken donburi', 14)
insert into CombineSP values ('Philadelphia maki', 14)
insert into CombineSP values ('California maki', 14)
insert into CombineSP values ('Mushroom Risotto', 14)
insert into CombineSP values ('Pork sausage roll', 14)
insert into CombineSP values ('Fettuccine Alfredo', 14)
insert into CombineSP values ('Risotto with seafood', 14)
insert into CombineSP values ('Vegetable Soup', 14)
insert into CombineSP values ('Tiramisù', 14)
insert into CombineSP values ('Cheeseburger', 14)
insert into CombineSP values ('Tuna sashimi', 14)
insert into CombineSP values ('Chilli con carne', 14)
insert into CombineSP values ('Pasta and Beans', 14)
insert into CombineSP values ('Fish and chips', 14)
insert into CombineSP values ('Lasagne', 14)
insert into CombineSP values ('Pasta with Tomato and Basil', 14)
insert into CombineSP values ('Souvlaki', 14)
insert into CombineSP values ('Chicken milanese', 14)
insert into CombineSP values ('Salmon nigiri', 14)
insert into CombineSP values ('Caesar Salad', 14)
insert into CombineSP values ('Chicken Fajitas', 14)
insert into CombineSP values ('Pork belly buns', 14)
insert into CombineSP values ('Ricotta stuffed Ravioli', 14)
insert into CombineSP values ('Caprese Salad', 14)
insert into CombineSP values ('Ebiten maki', 14)
insert into CombineSP values ('Barbecue Ribs', 14)
insert into CombineSP values ('Scotch eggs', 14)
insert into CombineSP values ('Katsu Curry', 14)
insert into CombineSP values ('Pasta Carbonara', 14)
insert into CombineSP values ('Bruschette with Tomato', 14)
insert into CombineSP values ('Pappardelle alla Bolognese', 14)
insert into CombineSP values ('Califlower penne', 14)
insert into CombineSP values ('Pizza', 14)
insert into CombineSP values ('Meatballs with sauce', 14)
insert into CombineSP values ('Chicken wings', 14)
insert into CombineSP values ('French fries with sausages', 15)
insert into CombineSP values ('Linguine with clams', 15)
insert into CombineSP values ('Teriyaki Chicken donburi', 15)
insert into CombineSP values ('Philadelphia maki', 15)
insert into CombineSP values ('California maki', 15)
insert into CombineSP values ('Mushroom Risotto', 15)
insert into CombineSP values ('Pork sausage roll', 15)
insert into CombineSP values ('Fettuccine Alfredo', 15)
insert into CombineSP values ('Risotto with seafood', 15)
insert into CombineSP values ('Vegetable Soup', 15)
insert into CombineSP values ('Tiramisù', 15)
insert into CombineSP values ('Cheeseburger', 15)
insert into CombineSP values ('Tuna sashimi', 15)
insert into CombineSP values ('Chilli con carne', 15)
insert into CombineSP values ('Pasta and Beans', 15)
insert into CombineSP values ('Fish and chips', 15)
insert into CombineSP values ('Lasagne', 15)
insert into CombineSP values ('Pasta with Tomato and Basil', 15)
insert into CombineSP values ('Souvlaki', 15)
insert into CombineSP values ('Chicken milanese', 15)
insert into CombineSP values ('Salmon nigiri', 15)
insert into CombineSP values ('Caesar Salad', 15)
insert into CombineSP values ('Chicken Fajitas', 15)
insert into CombineSP values ('Pork belly buns', 15)
insert into CombineSP values ('Ricotta stuffed Ravioli', 15)
insert into CombineSP values ('Caprese Salad', 15)
insert into CombineSP values ('Ebiten maki', 15)
insert into CombineSP values ('Barbecue Ribs', 15)
insert into CombineSP values ('Scotch eggs', 15)
insert into CombineSP values ('Katsu Curry', 15)
insert into CombineSP values ('Pasta Carbonara', 15)
insert into CombineSP values ('Bruschette with Tomato', 15)
insert into CombineSP values ('Pappardelle alla Bolognese', 15)
insert into CombineSP values ('Califlower penne', 15)
insert into CombineSP values ('Pizza', 15)
insert into CombineSP values ('Meatballs with sauce', 15)
insert into CombineSP values ('Chicken wings', 15)
