insert into CombineIP values ('Philadelphia maki', 1)
insert into CombineIP values ('California maki', 1)
insert into CombineIP values ('Mushroom Risotto', 1)
insert into CombineIP values ('Pork sausage roll', 1)
insert into CombineIP values ('Fettuccine Alfredo', 1)
insert into CombineIP values ('Tiramisù', 1)
insert into CombineIP values ('Cheeseburger', 1)
insert into CombineIP values ('Fish and chips', 1)
insert into CombineIP values ('Lasagne', 1)
insert into CombineIP values ('Pasta with Tomato and Basil', 1)
insert into CombineIP values ('Souvlaki', 1)
insert into CombineIP values ('Salmon nigiri', 1)
insert into CombineIP values ('Caesar Salad', 1)
insert into CombineIP values ('Caprese Salad', 1)
insert into CombineIP values ('Ebiten maki', 1)
insert into CombineIP values ('Barbecue Ribs', 1)
insert into CombineIP values ('Katsu Curry', 1)
insert into CombineIP values ('Bruschette with Tomato', 1)
insert into CombineIP values ('Pappardelle alla Bolognese', 1)
insert into CombineIP values ('Meatballs with sauce', 1)
insert into CombineIP values ('Chicken wings', 1)
insert into CombineIP values ('French fries with sausages', 2)
insert into CombineIP values ('Teriyaki Chicken donburi', 2)
insert into CombineIP values ('Philadelphia maki', 2)
insert into CombineIP values ('California maki', 2)
insert into CombineIP values ('Pork sausage roll', 2)
insert into CombineIP values ('Vegetable Soup', 2)
insert into CombineIP values ('Tuna sashimi', 2)
insert into CombineIP values ('Chilli con carne', 2)
insert into CombineIP values ('Pasta and Beans', 2)
insert into CombineIP values ('Fish and chips', 2)
insert into CombineIP values ('Pasta with Tomato and Basil', 2)
insert into CombineIP values ('Salmon nigiri', 2)
insert into CombineIP values ('Caesar Salad', 2)
insert into CombineIP values ('Chicken Fajitas', 2)
insert into CombineIP values ('Caprese Salad', 2)
insert into CombineIP values ('Barbecue Ribs', 2)
insert into CombineIP values ('Scotch eggs', 2)
insert into CombineIP values ('Bruschette with Tomato', 2)
insert into CombineIP values ('Pappardelle alla Bolognese', 2)
insert into CombineIP values ('Meatballs with sauce', 2)
insert into CombineIP values ('Linguine with clams', 3)
insert into CombineIP values ('Philadelphia maki', 3)
insert into CombineIP values ('Vegetable Soup', 3)
insert into CombineIP values ('Cheeseburger', 3)
insert into CombineIP values ('Tuna sashimi', 3)
insert into CombineIP values ('Fish and chips', 3)
insert into CombineIP values ('Lasagne', 3)
insert into CombineIP values ('Pasta with Tomato and Basil', 3)
insert into CombineIP values ('Souvlaki', 3)
insert into CombineIP values ('Chicken milanese', 3)
insert into CombineIP values ('Caesar Salad', 3)
insert into CombineIP values ('Ricotta stuffed Ravioli', 3)
insert into CombineIP values ('Barbecue Ribs', 3)
insert into CombineIP values ('Katsu Curry', 3)
insert into CombineIP values ('Pappardelle alla Bolognese', 3)
insert into CombineIP values ('Pizza', 3)
insert into CombineIP values ('Chicken wings', 3)
insert into CombineIP values ('French fries with sausages', 4)
insert into CombineIP values ('Teriyaki Chicken donburi', 4)
insert into CombineIP values ('Philadelphia maki', 4)
insert into CombineIP values ('California maki', 4)
insert into CombineIP values ('Risotto with seafood', 4)
insert into CombineIP values ('Vegetable Soup', 4)
insert into CombineIP values ('Tiramisù', 4)
insert into CombineIP values ('Tuna sashimi', 4)
insert into CombineIP values ('Pasta and Beans', 4)
insert into CombineIP values ('Souvlaki', 4)
insert into CombineIP values ('Chicken milanese', 4)
insert into CombineIP values ('Caesar Salad', 4)
insert into CombineIP values ('Caprese Salad', 4)
insert into CombineIP values ('Katsu Curry', 4)
insert into CombineIP values ('Bruschette with Tomato', 4)
insert into CombineIP values ('Califlower penne', 4)
insert into CombineIP values ('Pizza', 4)
insert into CombineIP values ('French fries with sausages', 5)
insert into CombineIP values ('Linguine with clams', 5)
insert into CombineIP values ('Philadelphia maki', 5)
insert into CombineIP values ('California maki', 5)
insert into CombineIP values ('Risotto with seafood', 5)
insert into CombineIP values ('Tiramisù', 5)
insert into CombineIP values ('Tuna sashimi', 5)
insert into CombineIP values ('Pasta and Beans', 5)
insert into CombineIP values ('Fish and chips', 5)
insert into CombineIP values ('Lasagne', 5)
insert into CombineIP values ('Pasta with Tomato and Basil', 5)
insert into CombineIP values ('Souvlaki', 5)
insert into CombineIP values ('Caprese Salad', 5)
insert into CombineIP values ('Ebiten maki', 5)
insert into CombineIP values ('Scotch eggs', 5)
insert into CombineIP values ('Katsu Curry', 5)
insert into CombineIP values ('Pasta Carbonara', 5)
insert into CombineIP values ('Bruschette with Tomato', 5)
insert into CombineIP values ('Pappardelle alla Bolognese', 5)
insert into CombineIP values ('Pizza', 5)
insert into CombineIP values ('Chicken wings', 5)
insert into CombineIP values ('French fries with sausages', 6)
insert into CombineIP values ('Linguine with clams', 6)
insert into CombineIP values ('Teriyaki Chicken donburi', 6)
insert into CombineIP values ('California maki', 6)
insert into CombineIP values ('Pork sausage roll', 6)
insert into CombineIP values ('Vegetable Soup', 6)
insert into CombineIP values ('Cheeseburger', 6)
insert into CombineIP values ('Tuna sashimi', 6)
insert into CombineIP values ('Chilli con carne', 6)
insert into CombineIP values ('Pasta and Beans', 6)
insert into CombineIP values ('Salmon nigiri', 6)
insert into CombineIP values ('Pork belly buns', 6)
insert into CombineIP values ('Barbecue Ribs', 6)
insert into CombineIP values ('Scotch eggs', 6)
insert into CombineIP values ('Katsu Curry', 6)
insert into CombineIP values ('Pasta Carbonara', 6)
insert into CombineIP values ('Bruschette with Tomato', 6)
insert into CombineIP values ('Pappardelle alla Bolognese', 6)
insert into CombineIP values ('Linguine with clams', 7)
insert into CombineIP values ('Fettuccine Alfredo', 7)
insert into CombineIP values ('Tiramisù', 7)
insert into CombineIP values ('Fish and chips', 7)
insert into CombineIP values ('Pasta with Tomato and Basil', 7)
insert into CombineIP values ('Chicken milanese', 7)
insert into CombineIP values ('Salmon nigiri', 7)
insert into CombineIP values ('Pork belly buns', 7)
insert into CombineIP values ('Caprese Salad', 7)
insert into CombineIP values ('Ebiten maki', 7)
insert into CombineIP values ('Barbecue Ribs', 7)
insert into CombineIP values ('Scotch eggs', 7)
insert into CombineIP values ('Katsu Curry', 7)
insert into CombineIP values ('Pizza', 7)
insert into CombineIP values ('Chicken wings', 7)
insert into CombineIP values ('California maki', 8)
insert into CombineIP values ('Mushroom Risotto', 8)
insert into CombineIP values ('Pork sausage roll', 8)
insert into CombineIP values ('Fettuccine Alfredo', 8)
insert into CombineIP values ('Vegetable Soup', 8)
insert into CombineIP values ('Cheeseburger', 8)
insert into CombineIP values ('Pasta and Beans', 8)
insert into CombineIP values ('Fish and chips', 8)
insert into CombineIP values ('Souvlaki', 8)
insert into CombineIP values ('Salmon nigiri', 8)
insert into CombineIP values ('Pork belly buns', 8)
insert into CombineIP values ('Ebiten maki', 8)
insert into CombineIP values ('Scotch eggs', 8)
insert into CombineIP values ('Pasta Carbonara', 8)
insert into CombineIP values ('Pizza', 8)
insert into CombineIP values ('Meatballs with sauce', 8)
insert into CombineIP values ('Philadelphia maki', 9)
insert into CombineIP values ('California maki', 9)
insert into CombineIP values ('Pork sausage roll', 9)
insert into CombineIP values ('Tiramisù', 9)
insert into CombineIP values ('Cheeseburger', 9)
insert into CombineIP values ('Tuna sashimi', 9)
insert into CombineIP values ('Chilli con carne', 9)
insert into CombineIP values ('Pasta and Beans', 9)
insert into CombineIP values ('Fish and chips', 9)
insert into CombineIP values ('Lasagne', 9)
insert into CombineIP values ('Pasta with Tomato and Basil', 9)
insert into CombineIP values ('Salmon nigiri', 9)
insert into CombineIP values ('Caesar Salad', 9)
insert into CombineIP values ('Chicken Fajitas', 9)
insert into CombineIP values ('Pork belly buns', 9)
insert into CombineIP values ('Ricotta stuffed Ravioli', 9)
insert into CombineIP values ('Ebiten maki', 9)
insert into CombineIP values ('Barbecue Ribs', 9)
insert into CombineIP values ('Pasta Carbonara', 9)
insert into CombineIP values ('Bruschette with Tomato', 9)
insert into CombineIP values ('Pappardelle alla Bolognese', 9)
insert into CombineIP values ('Califlower penne', 9)
insert into CombineIP values ('Pizza', 9)
insert into CombineIP values ('Meatballs with sauce', 9)
insert into CombineIP values ('Chicken wings', 9)
insert into CombineIP values ('Teriyaki Chicken donburi', 10)
insert into CombineIP values ('California maki', 10)
insert into CombineIP values ('Mushroom Risotto', 10)
insert into CombineIP values ('Fettuccine Alfredo', 10)
insert into CombineIP values ('Tiramisù', 10)
insert into CombineIP values ('Cheeseburger', 10)
insert into CombineIP values ('Tuna sashimi', 10)
insert into CombineIP values ('Fish and chips', 10)
insert into CombineIP values ('Lasagne', 10)
insert into CombineIP values ('Chicken milanese', 10)
insert into CombineIP values ('Salmon nigiri', 10)
insert into CombineIP values ('Caesar Salad', 10)
insert into CombineIP values ('Chicken Fajitas', 10)
insert into CombineIP values ('Pork belly buns', 10)
insert into CombineIP values ('Ricotta stuffed Ravioli', 10)
insert into CombineIP values ('Caprese Salad', 10)
insert into CombineIP values ('Barbecue Ribs', 10)
insert into CombineIP values ('Scotch eggs', 10)
insert into CombineIP values ('Bruschette with Tomato', 10)
insert into CombineIP values ('Pappardelle alla Bolognese', 10)
insert into CombineIP values ('Califlower penne', 10)
insert into CombineIP values ('Pizza', 10)
insert into CombineIP values ('Meatballs with sauce', 10)
insert into CombineIP values ('Teriyaki Chicken donburi', 11)
insert into CombineIP values ('California maki', 11)
insert into CombineIP values ('Fettuccine Alfredo', 11)
insert into CombineIP values ('Risotto with seafood', 11)
insert into CombineIP values ('Vegetable Soup', 11)
insert into CombineIP values ('Cheeseburger', 11)
insert into CombineIP values ('Pasta and Beans', 11)
insert into CombineIP values ('Fish and chips', 11)
insert into CombineIP values ('Souvlaki', 11)
insert into CombineIP values ('Salmon nigiri', 11)
insert into CombineIP values ('Chicken Fajitas', 11)
insert into CombineIP values ('Pork belly buns', 11)
insert into CombineIP values ('Ricotta stuffed Ravioli', 11)
insert into CombineIP values ('Ebiten maki', 11)
insert into CombineIP values ('Katsu Curry', 11)
insert into CombineIP values ('Bruschette with Tomato', 11)
insert into CombineIP values ('Pappardelle alla Bolognese', 11)
insert into CombineIP values ('Meatballs with sauce', 11)
insert into CombineIP values ('Chicken wings', 11)
insert into CombineIP values ('French fries with sausages', 12)
insert into CombineIP values ('Linguine with clams', 12)
insert into CombineIP values ('Philadelphia maki', 12)
insert into CombineIP values ('Pork sausage roll', 12)
insert into CombineIP values ('Fettuccine Alfredo', 12)
insert into CombineIP values ('Risotto with seafood', 12)
insert into CombineIP values ('Cheeseburger', 12)
insert into CombineIP values ('Fish and chips', 12)
insert into CombineIP values ('Pasta with Tomato and Basil', 12)
insert into CombineIP values ('Chicken milanese', 12)
insert into CombineIP values ('Caesar Salad', 12)
insert into CombineIP values ('Caprese Salad', 12)
insert into CombineIP values ('Pasta Carbonara', 12)
insert into CombineIP values ('Bruschette with Tomato', 12)
insert into CombineIP values ('Califlower penne', 12)
insert into CombineIP values ('Pizza', 12)
insert into CombineIP values ('Meatballs with sauce', 12)
insert into CombineIP values ('Chicken wings', 12)
insert into CombineIP values ('French fries with sausages', 13)
insert into CombineIP values ('California maki', 13)
insert into CombineIP values ('Mushroom Risotto', 13)
insert into CombineIP values ('Pork sausage roll', 13)
insert into CombineIP values ('Risotto with seafood', 13)
insert into CombineIP values ('Tuna sashimi', 13)
insert into CombineIP values ('Chilli con carne', 13)
insert into CombineIP values ('Lasagne', 13)
insert into CombineIP values ('Souvlaki', 13)
insert into CombineIP values ('Chicken milanese', 13)
insert into CombineIP values ('Caesar Salad', 13)
insert into CombineIP values ('Pork belly buns', 13)
insert into CombineIP values ('Caprese Salad', 13)
insert into CombineIP values ('Ebiten maki', 13)
insert into CombineIP values ('Katsu Curry', 13)
insert into CombineIP values ('Pappardelle alla Bolognese', 13)
insert into CombineIP values ('Chicken wings', 13)
insert into CombineIP values ('French fries with sausages', 14)
insert into CombineIP values ('Linguine with clams', 14)
insert into CombineIP values ('California maki', 14)
insert into CombineIP values ('Fettuccine Alfredo', 14)
insert into CombineIP values ('Vegetable Soup', 14)
insert into CombineIP values ('Chilli con carne', 14)
insert into CombineIP values ('Chicken milanese', 14)
insert into CombineIP values ('Salmon nigiri', 14)
insert into CombineIP values ('Caesar Salad', 14)
insert into CombineIP values ('Pork belly buns', 14)
insert into CombineIP values ('Caprese Salad', 14)
insert into CombineIP values ('Ebiten maki', 14)
insert into CombineIP values ('Barbecue Ribs', 14)
insert into CombineIP values ('Scotch eggs', 14)
insert into CombineIP values ('Katsu Curry', 14)
insert into CombineIP values ('Pasta Carbonara', 14)
insert into CombineIP values ('Bruschette with Tomato', 14)
insert into CombineIP values ('Meatballs with sauce', 14)
insert into CombineIP values ('Linguine with clams', 15)
insert into CombineIP values ('Teriyaki Chicken donburi', 15)
insert into CombineIP values ('California maki', 15)
insert into CombineIP values ('Fettuccine Alfredo', 15)
insert into CombineIP values ('Tiramisù', 15)
insert into CombineIP values ('Caesar Salad', 15)
insert into CombineIP values ('Ebiten maki', 15)
insert into CombineIP values ('Barbecue Ribs', 15)
insert into CombineIP values ('Scotch eggs', 15)
insert into CombineIP values ('Pappardelle alla Bolognese', 15)
insert into CombineIP values ('Califlower penne', 15)
insert into CombineIP values ('Linguine with clams', 16)
insert into CombineIP values ('Teriyaki Chicken donburi', 16)
insert into CombineIP values ('Philadelphia maki', 16)
insert into CombineIP values ('California maki', 16)
insert into CombineIP values ('Risotto with seafood', 16)
insert into CombineIP values ('Chilli con carne', 16)
insert into CombineIP values ('Fish and chips', 16)
insert into CombineIP values ('Pasta with Tomato and Basil', 16)
insert into CombineIP values ('Souvlaki', 16)
insert into CombineIP values ('Chicken milanese', 16)
insert into CombineIP values ('Chicken Fajitas', 16)
insert into CombineIP values ('Pork belly buns', 16)
insert into CombineIP values ('Ebiten maki', 16)
insert into CombineIP values ('Pasta Carbonara', 16)
insert into CombineIP values ('Pappardelle alla Bolognese', 16)
insert into CombineIP values ('Califlower penne', 16)
insert into CombineIP values ('Pizza', 16)
insert into CombineIP values ('Meatballs with sauce', 16)
insert into CombineIP values ('Chicken wings', 16)
insert into CombineIP values ('Linguine with clams', 17)
insert into CombineIP values ('California maki', 17)
insert into CombineIP values ('Pork sausage roll', 17)
insert into CombineIP values ('Tiramisù', 17)
insert into CombineIP values ('Cheeseburger', 17)
insert into CombineIP values ('Tuna sashimi', 17)
insert into CombineIP values ('Chilli con carne', 17)
insert into CombineIP values ('Souvlaki', 17)
insert into CombineIP values ('Chicken milanese', 17)
insert into CombineIP values ('Caesar Salad', 17)
insert into CombineIP values ('Chicken Fajitas', 17)
insert into CombineIP values ('Pork belly buns', 17)
insert into CombineIP values ('Caprese Salad', 17)
insert into CombineIP values ('Ebiten maki', 17)
insert into CombineIP values ('Scotch eggs', 17)
insert into CombineIP values ('Bruschette with Tomato', 17)
insert into CombineIP values ('Pizza', 17)
insert into CombineIP values ('Meatballs with sauce', 17)
insert into CombineIP values ('Chicken wings', 17)
insert into CombineIP values ('French fries with sausages', 18)
insert into CombineIP values ('Linguine with clams', 18)
insert into CombineIP values ('California maki', 18)
insert into CombineIP values ('Fettuccine Alfredo', 18)
insert into CombineIP values ('Risotto with seafood', 18)
insert into CombineIP values ('Tiramisù', 18)
insert into CombineIP values ('Tuna sashimi', 18)
insert into CombineIP values ('Pasta and Beans', 18)
insert into CombineIP values ('Pasta with Tomato and Basil', 18)
insert into CombineIP values ('Souvlaki', 18)
insert into CombineIP values ('Chicken milanese', 18)
insert into CombineIP values ('Caesar Salad', 18)
insert into CombineIP values ('Pork belly buns', 18)
insert into CombineIP values ('Ricotta stuffed Ravioli', 18)
insert into CombineIP values ('Caprese Salad', 18)
insert into CombineIP values ('Scotch eggs', 18)
insert into CombineIP values ('Bruschette with Tomato', 18)
insert into CombineIP values ('Chicken wings', 18)
insert into CombineIP values ('Teriyaki Chicken donburi', 19)
insert into CombineIP values ('Pork sausage roll', 19)
insert into CombineIP values ('Tiramisù', 19)
insert into CombineIP values ('Chilli con carne', 19)
insert into CombineIP values ('Fish and chips', 19)
insert into CombineIP values ('Lasagne', 19)
insert into CombineIP values ('Pasta with Tomato and Basil', 19)
insert into CombineIP values ('Caesar Salad', 19)
insert into CombineIP values ('Pork belly buns', 19)
insert into CombineIP values ('Ricotta stuffed Ravioli', 19)
insert into CombineIP values ('Caprese Salad', 19)
insert into CombineIP values ('Ebiten maki', 19)
insert into CombineIP values ('Katsu Curry', 19)
insert into CombineIP values ('Bruschette with Tomato', 19)
insert into CombineIP values ('Pappardelle alla Bolognese', 19)
insert into CombineIP values ('Califlower penne', 19)
insert into CombineIP values ('Meatballs with sauce', 19)
insert into CombineIP values ('French fries with sausages', 20)
insert into CombineIP values ('Teriyaki Chicken donburi', 20)
insert into CombineIP values ('Pork sausage roll', 20)
insert into CombineIP values ('Fettuccine Alfredo', 20)
insert into CombineIP values ('Vegetable Soup', 20)
insert into CombineIP values ('Pasta and Beans', 20)
insert into CombineIP values ('Lasagne', 20)
insert into CombineIP values ('Pasta with Tomato and Basil', 20)
insert into CombineIP values ('Salmon nigiri', 20)
insert into CombineIP values ('Pork belly buns', 20)
insert into CombineIP values ('Caprese Salad', 20)
insert into CombineIP values ('Ebiten maki', 20)
insert into CombineIP values ('Barbecue Ribs', 20)
insert into CombineIP values ('Scotch eggs', 20)
insert into CombineIP values ('Katsu Curry', 20)
insert into CombineIP values ('Pasta Carbonara', 20)
insert into CombineIP values ('Meatballs with sauce', 20)
insert into CombineIP values ('Linguine with clams', 21)
insert into CombineIP values ('Teriyaki Chicken donburi', 21)
insert into CombineIP values ('Philadelphia maki', 21)
insert into CombineIP values ('California maki', 21)
insert into CombineIP values ('Mushroom Risotto', 21)
insert into CombineIP values ('Pork sausage roll', 21)
insert into CombineIP values ('Vegetable Soup', 21)
insert into CombineIP values ('Cheeseburger', 21)
insert into CombineIP values ('Chilli con carne', 21)
insert into CombineIP values ('Pasta and Beans', 21)
insert into CombineIP values ('Fish and chips', 21)
insert into CombineIP values ('Pasta with Tomato and Basil', 21)
insert into CombineIP values ('Chicken milanese', 21)
insert into CombineIP values ('Salmon nigiri', 21)
insert into CombineIP values ('Chicken Fajitas', 21)
insert into CombineIP values ('Barbecue Ribs', 21)
insert into CombineIP values ('Scotch eggs', 21)
insert into CombineIP values ('Katsu Curry', 21)
insert into CombineIP values ('Pappardelle alla Bolognese', 21)
insert into CombineIP values ('Meatballs with sauce', 21)
insert into CombineIP values ('Philadelphia maki', 22)
insert into CombineIP values ('Fettuccine Alfredo', 22)
insert into CombineIP values ('Risotto with seafood', 22)
insert into CombineIP values ('Tiramisù', 22)
insert into CombineIP values ('Chilli con carne', 22)
insert into CombineIP values ('Pasta and Beans', 22)
insert into CombineIP values ('Fish and chips', 22)
insert into CombineIP values ('Lasagne', 22)
insert into CombineIP values ('Souvlaki', 22)
insert into CombineIP values ('Caesar Salad', 22)
insert into CombineIP values ('Pork belly buns', 22)
insert into CombineIP values ('Caprese Salad', 22)
insert into CombineIP values ('Ebiten maki', 22)
insert into CombineIP values ('Barbecue Ribs', 22)
insert into CombineIP values ('Scotch eggs', 22)
insert into CombineIP values ('Katsu Curry', 22)
insert into CombineIP values ('Pasta Carbonara', 22)
insert into CombineIP values ('Pappardelle alla Bolognese', 22)
insert into CombineIP values ('French fries with sausages', 23)
insert into CombineIP values ('Linguine with clams', 23)
insert into CombineIP values ('Teriyaki Chicken donburi', 23)
insert into CombineIP values ('Philadelphia maki', 23)
insert into CombineIP values ('California maki', 23)
insert into CombineIP values ('Mushroom Risotto', 23)
insert into CombineIP values ('Pork sausage roll', 23)
insert into CombineIP values ('Fettuccine Alfredo', 23)
insert into CombineIP values ('Risotto with seafood', 23)
insert into CombineIP values ('Vegetable Soup', 23)
insert into CombineIP values ('Tiramisù', 23)
insert into CombineIP values ('Cheeseburger', 23)
insert into CombineIP values ('Pasta and Beans', 23)
insert into CombineIP values ('Fish and chips', 23)
insert into CombineIP values ('Lasagne', 23)
insert into CombineIP values ('Souvlaki', 23)
insert into CombineIP values ('Caprese Salad', 23)
insert into CombineIP values ('Ebiten maki', 23)
insert into CombineIP values ('Scotch eggs', 23)
insert into CombineIP values ('Bruschette with Tomato', 23)
insert into CombineIP values ('Califlower penne', 23)
insert into CombineIP values ('Linguine with clams', 24)
insert into CombineIP values ('California maki', 24)
insert into CombineIP values ('Mushroom Risotto', 24)
insert into CombineIP values ('Pork sausage roll', 24)
insert into CombineIP values ('Fettuccine Alfredo', 24)
insert into CombineIP values ('Vegetable Soup', 24)
insert into CombineIP values ('Cheeseburger', 24)
insert into CombineIP values ('Fish and chips', 24)
insert into CombineIP values ('Pasta with Tomato and Basil', 24)
insert into CombineIP values ('Souvlaki', 24)
insert into CombineIP values ('Salmon nigiri', 24)
insert into CombineIP values ('Ricotta stuffed Ravioli', 24)
insert into CombineIP values ('Ebiten maki', 24)
insert into CombineIP values ('Barbecue Ribs', 24)
insert into CombineIP values ('Scotch eggs', 24)
insert into CombineIP values ('Katsu Curry', 24)
insert into CombineIP values ('Pappardelle alla Bolognese', 24)
insert into CombineIP values ('Califlower penne', 24)
insert into CombineIP values ('Pizza', 24)
insert into CombineIP values ('Chicken wings', 24)
insert into CombineIP values ('French fries with sausages', 25)
insert into CombineIP values ('Teriyaki Chicken donburi', 25)
insert into CombineIP values ('Philadelphia maki', 25)
insert into CombineIP values ('California maki', 25)
insert into CombineIP values ('Mushroom Risotto', 25)
insert into CombineIP values ('Pork sausage roll', 25)
insert into CombineIP values ('Tiramisù', 25)
insert into CombineIP values ('Cheeseburger', 25)
insert into CombineIP values ('Tuna sashimi', 25)
insert into CombineIP values ('Chilli con carne', 25)
insert into CombineIP values ('Fish and chips', 25)
insert into CombineIP values ('Chicken Fajitas', 25)
insert into CombineIP values ('Pork belly buns', 25)
insert into CombineIP values ('Ricotta stuffed Ravioli', 25)
insert into CombineIP values ('Caprese Salad', 25)
insert into CombineIP values ('Ebiten maki', 25)
insert into CombineIP values ('Barbecue Ribs', 25)
insert into CombineIP values ('Scotch eggs', 25)
insert into CombineIP values ('Pizza', 25)
insert into CombineIP values ('Meatballs with sauce', 25)
insert into CombineIP values ('Chicken wings', 25)
insert into CombineIP values ('Teriyaki Chicken donburi', 26)
insert into CombineIP values ('California maki', 26)
insert into CombineIP values ('Fettuccine Alfredo', 26)
insert into CombineIP values ('Risotto with seafood', 26)
insert into CombineIP values ('Cheeseburger', 26)
insert into CombineIP values ('Chilli con carne', 26)
insert into CombineIP values ('Pasta with Tomato and Basil', 26)
insert into CombineIP values ('Salmon nigiri', 26)
insert into CombineIP values ('Caesar Salad', 26)
insert into CombineIP values ('Chicken Fajitas', 26)
insert into CombineIP values ('Caprese Salad', 26)
insert into CombineIP values ('Ebiten maki', 26)
insert into CombineIP values ('Bruschette with Tomato', 26)
insert into CombineIP values ('Pappardelle alla Bolognese', 26)
insert into CombineIP values ('Califlower penne', 26)
insert into CombineIP values ('Teriyaki Chicken donburi', 27)
insert into CombineIP values ('Philadelphia maki', 27)
insert into CombineIP values ('Pork sausage roll', 27)
insert into CombineIP values ('Fettuccine Alfredo', 27)
insert into CombineIP values ('Vegetable Soup', 27)
insert into CombineIP values ('Tiramisù', 27)
insert into CombineIP values ('Tuna sashimi', 27)
insert into CombineIP values ('Fish and chips', 27)
insert into CombineIP values ('Lasagne', 27)
insert into CombineIP values ('Salmon nigiri', 27)
insert into CombineIP values ('Chicken Fajitas', 27)
insert into CombineIP values ('Pork belly buns', 27)
insert into CombineIP values ('Ricotta stuffed Ravioli', 27)
insert into CombineIP values ('Caprese Salad', 27)
insert into CombineIP values ('Ebiten maki', 27)
insert into CombineIP values ('Barbecue Ribs', 27)
insert into CombineIP values ('Scotch eggs', 27)
insert into CombineIP values ('Katsu Curry', 27)
insert into CombineIP values ('Pasta Carbonara', 27)
insert into CombineIP values ('Bruschette with Tomato', 27)
insert into CombineIP values ('Pappardelle alla Bolognese', 27)
insert into CombineIP values ('Califlower penne', 27)
insert into CombineIP values ('Pizza', 27)
insert into CombineIP values ('Chicken wings', 27)
insert into CombineIP values ('Teriyaki Chicken donburi', 28)
insert into CombineIP values ('Philadelphia maki', 28)
insert into CombineIP values ('California maki', 28)
insert into CombineIP values ('Mushroom Risotto', 28)
insert into CombineIP values ('Fettuccine Alfredo', 28)
insert into CombineIP values ('Fish and chips', 28)
insert into CombineIP values ('Lasagne', 28)
insert into CombineIP values ('Chicken milanese', 28)
insert into CombineIP values ('Salmon nigiri', 28)
insert into CombineIP values ('Chicken Fajitas', 28)
insert into CombineIP values ('Pork belly buns', 28)
insert into CombineIP values ('Caprese Salad', 28)
insert into CombineIP values ('Ebiten maki', 28)
insert into CombineIP values ('Barbecue Ribs', 28)
insert into CombineIP values ('Scotch eggs', 28)
insert into CombineIP values ('Katsu Curry', 28)
insert into CombineIP values ('Pasta Carbonara', 28)
insert into CombineIP values ('Bruschette with Tomato', 28)
insert into CombineIP values ('Pappardelle alla Bolognese', 28)
insert into CombineIP values ('California maki', 29)
insert into CombineIP values ('Fettuccine Alfredo', 29)
insert into CombineIP values ('Vegetable Soup', 29)
insert into CombineIP values ('Cheeseburger', 29)
insert into CombineIP values ('Tuna sashimi', 29)
insert into CombineIP values ('Pasta and Beans', 29)
insert into CombineIP values ('Fish and chips', 29)
insert into CombineIP values ('Lasagne', 29)
insert into CombineIP values ('Pasta with Tomato and Basil', 29)
insert into CombineIP values ('Chicken milanese', 29)
insert into CombineIP values ('Chicken Fajitas', 29)
insert into CombineIP values ('Pork belly buns', 29)
insert into CombineIP values ('Ricotta stuffed Ravioli', 29)
insert into CombineIP values ('Caprese Salad', 29)
insert into CombineIP values ('Ebiten maki', 29)
insert into CombineIP values ('Pasta Carbonara', 29)
insert into CombineIP values ('Meatballs with sauce', 29)
insert into CombineIP values ('French fries with sausages', 30)
insert into CombineIP values ('Teriyaki Chicken donburi', 30)
insert into CombineIP values ('California maki', 30)
insert into CombineIP values ('Risotto with seafood', 30)
insert into CombineIP values ('Vegetable Soup', 30)
insert into CombineIP values ('Tuna sashimi', 30)
insert into CombineIP values ('Chilli con carne', 30)
insert into CombineIP values ('Pasta and Beans', 30)
insert into CombineIP values ('Lasagne', 30)
insert into CombineIP values ('Pasta with Tomato and Basil', 30)
insert into CombineIP values ('Souvlaki', 30)
insert into CombineIP values ('Caesar Salad', 30)
insert into CombineIP values ('Chicken Fajitas', 30)
insert into CombineIP values ('Ebiten maki', 30)
insert into CombineIP values ('Katsu Curry', 30)
insert into CombineIP values ('Califlower penne', 30)
insert into CombineIP values ('Pizza', 30)
insert into CombineIP values ('French fries with sausages', 31)
insert into CombineIP values ('Teriyaki Chicken donburi', 31)
insert into CombineIP values ('California maki', 31)
insert into CombineIP values ('Mushroom Risotto', 31)
insert into CombineIP values ('Fettuccine Alfredo', 31)
insert into CombineIP values ('Vegetable Soup', 31)
insert into CombineIP values ('Cheeseburger', 31)
insert into CombineIP values ('Tuna sashimi', 31)
insert into CombineIP values ('Pasta and Beans', 31)
insert into CombineIP values ('Chicken milanese', 31)
insert into CombineIP values ('Ricotta stuffed Ravioli', 31)
insert into CombineIP values ('Ebiten maki', 31)
insert into CombineIP values ('Pasta Carbonara', 31)
insert into CombineIP values ('Bruschette with Tomato', 31)
insert into CombineIP values ('Califlower penne', 31)
insert into CombineIP values ('Pizza', 31)
insert into CombineIP values ('French fries with sausages', 32)
insert into CombineIP values ('California maki', 32)
insert into CombineIP values ('Mushroom Risotto', 32)
insert into CombineIP values ('Risotto with seafood', 32)
insert into CombineIP values ('Tiramisù', 32)
insert into CombineIP values ('Tuna sashimi', 32)
insert into CombineIP values ('Fish and chips', 32)
insert into CombineIP values ('Lasagne', 32)
insert into CombineIP values ('Souvlaki', 32)
insert into CombineIP values ('Salmon nigiri', 32)
insert into CombineIP values ('Caesar Salad', 32)
insert into CombineIP values ('Chicken Fajitas', 32)
insert into CombineIP values ('Caprese Salad', 32)
insert into CombineIP values ('Califlower penne', 32)
insert into CombineIP values ('Pizza', 32)
insert into CombineIP values ('French fries with sausages', 33)
insert into CombineIP values ('Linguine with clams', 33)
insert into CombineIP values ('Teriyaki Chicken donburi', 33)
insert into CombineIP values ('Pork sausage roll', 33)
insert into CombineIP values ('Risotto with seafood', 33)
insert into CombineIP values ('Vegetable Soup', 33)
insert into CombineIP values ('Cheeseburger', 33)
insert into CombineIP values ('Tuna sashimi', 33)
insert into CombineIP values ('Pasta and Beans', 33)
insert into CombineIP values ('Lasagne', 33)
insert into CombineIP values ('Souvlaki', 33)
insert into CombineIP values ('Chicken Fajitas', 33)
insert into CombineIP values ('Pork belly buns', 33)
insert into CombineIP values ('Barbecue Ribs', 33)
insert into CombineIP values ('Scotch eggs', 33)
insert into CombineIP values ('Pappardelle alla Bolognese', 33)
insert into CombineIP values ('Califlower penne', 33)
insert into CombineIP values ('Chicken wings', 33)
insert into CombineIP values ('French fries with sausages', 34)
insert into CombineIP values ('Linguine with clams', 34)
insert into CombineIP values ('Teriyaki Chicken donburi', 34)
insert into CombineIP values ('Pork sausage roll', 34)
insert into CombineIP values ('Vegetable Soup', 34)
insert into CombineIP values ('Tiramisù', 34)
insert into CombineIP values ('Tuna sashimi', 34)
insert into CombineIP values ('Chilli con carne', 34)
insert into CombineIP values ('Pasta and Beans', 34)
insert into CombineIP values ('Fish and chips', 34)
insert into CombineIP values ('Pasta with Tomato and Basil', 34)
insert into CombineIP values ('Salmon nigiri', 34)
insert into CombineIP values ('Chicken Fajitas', 34)
insert into CombineIP values ('Ricotta stuffed Ravioli', 34)
insert into CombineIP values ('Ebiten maki', 34)
insert into CombineIP values ('Barbecue Ribs', 34)
insert into CombineIP values ('Katsu Curry', 34)
insert into CombineIP values ('Pasta Carbonara', 34)
insert into CombineIP values ('Pappardelle alla Bolognese', 34)
insert into CombineIP values ('Califlower penne', 34)
insert into CombineIP values ('Pizza', 34)
insert into CombineIP values ('Meatballs with sauce', 34)
insert into CombineIP values ('Chicken wings', 34)
