insert into Contient values (1, 'French fries with sausages')
insert into Contient values (1, 'Philadelphia maki')
insert into Contient values (1, 'Pork sausage roll')
insert into Contient values (1, 'Fettuccine Alfredo')
insert into Contient values (1, 'Risotto with seafood')
insert into Contient values (1, 'Vegetable Soup')
insert into Contient values (1, 'Tiramisù')
insert into Contient values (1, 'Cheeseburger')
insert into Contient values (1, 'Tuna sashimi')
insert into Contient values (1, 'Chilli con carne')
insert into Contient values (1, 'Fish and chips')
insert into Contient values (1, 'Lasagne')
insert into Contient values (1, 'Pasta with Tomato and Basil')
insert into Contient values (1, 'Souvlaki')
insert into Contient values (1, 'Chicken milanese')
insert into Contient values (1, 'Salmon nigiri')
insert into Contient values (1, 'Caesar Salad')
insert into Contient values (1, 'Chicken Fajitas')
insert into Contient values (1, 'Pork belly buns')
insert into Contient values (1, 'Ricotta stuffed Ravioli')
insert into Contient values (1, 'Ebiten maki')
insert into Contient values (1, 'Barbecue Ribs')
insert into Contient values (1, 'Scotch eggs')
insert into Contient values (1, 'Pappardelle alla Bolognese')
insert into Contient values (1, 'Chicken wings')
insert into Contient values (2, 'Linguine with clams')
insert into Contient values (2, 'California maki')
insert into Contient values (2, 'Fettuccine Alfredo')
insert into Contient values (2, 'Risotto with seafood')
insert into Contient values (2, 'Tiramisù')
insert into Contient values (2, 'Tuna sashimi')
insert into Contient values (2, 'Fish and chips')
insert into Contient values (2, 'Souvlaki')
insert into Contient values (2, 'Chicken milanese')
insert into Contient values (2, 'Salmon nigiri')
insert into Contient values (2, 'Caesar Salad')
insert into Contient values (2, 'Chicken Fajitas')
insert into Contient values (2, 'Pork belly buns')
insert into Contient values (2, 'Ricotta stuffed Ravioli')
insert into Contient values (2, 'Caprese Salad')
insert into Contient values (2, 'Ebiten maki')
insert into Contient values (2, 'Barbecue Ribs')
insert into Contient values (2, 'Califlower penne')
insert into Contient values (2, 'Pizza')
insert into Contient values (2, 'Meatballs with sauce')
insert into Contient values (3, 'Linguine with clams')
insert into Contient values (3, 'California maki')
insert into Contient values (3, 'Fettuccine Alfredo')
insert into Contient values (3, 'Vegetable Soup')
insert into Contient values (3, 'Tiramisù')
insert into Contient values (3, 'Cheeseburger')
insert into Contient values (3, 'Pasta and Beans')
insert into Contient values (3, 'Lasagne')
insert into Contient values (3, 'Chicken Fajitas')
insert into Contient values (3, 'Ricotta stuffed Ravioli')
insert into Contient values (3, 'Caprese Salad')
insert into Contient values (3, 'Ebiten maki')
insert into Contient values (3, 'Barbecue Ribs')
insert into Contient values (3, 'Pasta Carbonara')
insert into Contient values (3, 'Bruschette with Tomato')
insert into Contient values (3, 'Califlower penne')
insert into Contient values (3, 'Pizza')
insert into Contient values (4, 'Philadelphia maki')
insert into Contient values (4, 'Mushroom Risotto')
insert into Contient values (4, 'Pork sausage roll')
insert into Contient values (4, 'Tuna sashimi')
insert into Contient values (4, 'Chilli con carne')
insert into Contient values (4, 'Pasta and Beans')
insert into Contient values (4, 'Fish and chips')
insert into Contient values (4, 'Lasagne')
insert into Contient values (4, 'Chicken Fajitas')
insert into Contient values (4, 'Pork belly buns')
insert into Contient values (4, 'Caprese Salad')
insert into Contient values (4, 'Barbecue Ribs')
insert into Contient values (4, 'Katsu Curry')
insert into Contient values (4, 'Pizza')
insert into Contient values (4, 'Chicken wings')
insert into Contient values (5, 'French fries with sausages')
insert into Contient values (5, 'Linguine with clams')
insert into Contient values (5, 'Risotto with seafood')
insert into Contient values (5, 'Tiramisù')
insert into Contient values (5, 'Pasta and Beans')
insert into Contient values (5, 'Fish and chips')
insert into Contient values (5, 'Lasagne')
insert into Contient values (5, 'Pasta with Tomato and Basil')
insert into Contient values (5, 'Souvlaki')
insert into Contient values (5, 'Chicken milanese')
insert into Contient values (5, 'Caesar Salad')
insert into Contient values (5, 'Ebiten maki')
insert into Contient values (5, 'Barbecue Ribs')
insert into Contient values (5, 'Scotch eggs')
insert into Contient values (5, 'Katsu Curry')
insert into Contient values (5, 'Pizza')
insert into Contient values (5, 'Chicken wings')
insert into Contient values (6, 'French fries with sausages')
insert into Contient values (6, 'Linguine with clams')
insert into Contient values (6, 'California maki')
insert into Contient values (6, 'Mushroom Risotto')
insert into Contient values (6, 'Pork sausage roll')
insert into Contient values (6, 'Cheeseburger')
insert into Contient values (6, 'Tuna sashimi')
insert into Contient values (6, 'Chilli con carne')
insert into Contient values (6, 'Pasta and Beans')
insert into Contient values (6, 'Pasta with Tomato and Basil')
insert into Contient values (6, 'Caesar Salad')
insert into Contient values (6, 'Chicken Fajitas')
insert into Contient values (6, 'Scotch eggs')
insert into Contient values (6, 'Bruschette with Tomato')
insert into Contient values (6, 'Califlower penne')
insert into Contient values (6, 'Pizza')
insert into Contient values (6, 'Chicken wings')
insert into Contient values (7, 'French fries with sausages')
insert into Contient values (7, 'Linguine with clams')
insert into Contient values (7, 'Teriyaki Chicken donburi')
insert into Contient values (7, 'Philadelphia maki')
insert into Contient values (7, 'Risotto with seafood')
insert into Contient values (7, 'Vegetable Soup')
insert into Contient values (7, 'Tiramisù')
insert into Contient values (7, 'Chilli con carne')
insert into Contient values (7, 'Fish and chips')
insert into Contient values (7, 'Lasagne')
insert into Contient values (7, 'Pasta with Tomato and Basil')
insert into Contient values (7, 'Salmon nigiri')
insert into Contient values (7, 'Caesar Salad')
insert into Contient values (7, 'Chicken Fajitas')
insert into Contient values (7, 'Ebiten maki')
insert into Contient values (7, 'Scotch eggs')
insert into Contient values (7, 'Katsu Curry')
insert into Contient values (7, 'Pasta Carbonara')
insert into Contient values (7, 'Bruschette with Tomato')
insert into Contient values (7, 'Califlower penne')
insert into Contient values (8, 'French fries with sausages')
insert into Contient values (8, 'Philadelphia maki')
insert into Contient values (8, 'Mushroom Risotto')
insert into Contient values (8, 'Risotto with seafood')
insert into Contient values (8, 'Tiramisù')
insert into Contient values (8, 'Cheeseburger')
insert into Contient values (8, 'Tuna sashimi')
insert into Contient values (8, 'Pasta with Tomato and Basil')
insert into Contient values (8, 'Souvlaki')
insert into Contient values (8, 'Salmon nigiri')
insert into Contient values (8, 'Caesar Salad')
insert into Contient values (8, 'Ricotta stuffed Ravioli')
insert into Contient values (8, 'Caprese Salad')
insert into Contient values (8, 'Ebiten maki')
insert into Contient values (8, 'Scotch eggs')
insert into Contient values (8, 'Katsu Curry')
insert into Contient values (8, 'Bruschette with Tomato')
insert into Contient values (8, 'Pizza')
insert into Contient values (8, 'Chicken wings')
insert into Contient values (9, 'Mushroom Risotto')
insert into Contient values (9, 'Vegetable Soup')
insert into Contient values (9, 'Tiramisù')
insert into Contient values (9, 'Cheeseburger')
insert into Contient values (9, 'Tuna sashimi')
insert into Contient values (9, 'Chilli con carne')
insert into Contient values (9, 'Fish and chips')
insert into Contient values (9, 'Pasta with Tomato and Basil')
insert into Contient values (9, 'Souvlaki')
insert into Contient values (9, 'Salmon nigiri')
insert into Contient values (9, 'Caesar Salad')
insert into Contient values (9, 'Caprese Salad')
insert into Contient values (9, 'Barbecue Ribs')
insert into Contient values (9, 'Katsu Curry')
insert into Contient values (9, 'Pappardelle alla Bolognese')
insert into Contient values (9, 'Pizza')
insert into Contient values (10, 'French fries with sausages')
insert into Contient values (10, 'California maki')
insert into Contient values (10, 'Mushroom Risotto')
insert into Contient values (10, 'Pork sausage roll')
insert into Contient values (10, 'Vegetable Soup')
insert into Contient values (10, 'Tiramisù')
insert into Contient values (10, 'Cheeseburger')
insert into Contient values (10, 'Pasta and Beans')
insert into Contient values (10, 'Fish and chips')
insert into Contient values (10, 'Pasta with Tomato and Basil')
insert into Contient values (10, 'Salmon nigiri')
insert into Contient values (10, 'Caesar Salad')
insert into Contient values (10, 'Ricotta stuffed Ravioli')
insert into Contient values (10, 'Ebiten maki')
insert into Contient values (10, 'Barbecue Ribs')
insert into Contient values (10, 'Scotch eggs')
insert into Contient values (10, 'Pappardelle alla Bolognese')
insert into Contient values (10, 'Califlower penne')
insert into Contient values (10, 'Pizza')
insert into Contient values (10, 'Chicken wings')
