insert into Est_Associe values (1, 'Traditionnel')
insert into Est_Associe values (1, 'Combiné 5-en-1')
insert into Est_Associe values (1, 'Bas de gamme')
insert into Est_Associe values (2, 'Traditionnel')
insert into Est_Associe values (2, 'Combiné 5-en-1')
insert into Est_Associe values (2, 'Bas de gamme')
insert into Est_Associe values (3, 'Traditionnel')
insert into Est_Associe values (3, 'Combiné 5-en-1')
insert into Est_Associe values (3, 'Bas de gamme')
insert into Est_Associe values (4, 'Traditionnel')
insert into Est_Associe values (4, 'Combiné 5-en-1')
insert into Est_Associe values (4, 'Bas de gamme')
insert into Est_Associe values (5, 'Traditionnel')
insert into Est_Associe values (5, 'Combiné 5-en-1')
insert into Est_Associe values (5, 'Bas de gamme')
insert into Est_Associe values (6, 'Traditionnel')
insert into Est_Associe values (6, 'Combiné 5-en-1')
insert into Est_Associe values (6, 'Bas de gamme')
insert into Est_Associe values (7, 'Traditionnel')
insert into Est_Associe values (7, 'Combiné 5-en-1')
insert into Est_Associe values (7, 'Bas de gamme')
insert into Est_Associe values (8, 'Traditionnel')
insert into Est_Associe values (8, 'Combiné 5-en-1')
insert into Est_Associe values (8, 'Bas de gamme')
insert into Est_Associe values (9, 'Traditionnel')
insert into Est_Associe values (9, 'Combiné 5-en-1')
insert into Est_Associe values (9, 'Bas de gamme')
insert into Est_Associe values (10, 'Traditionnel')
insert into Est_Associe values (10, 'Combiné 5-en-1')
insert into Est_Associe values (10, 'Bas de gamme')
