insert into Ingredient values (1, 'Pomme de terre', 1)
insert into Ingredient values (2, 'Oignon', 1)
insert into Ingredient values (3, 'Cornichon', 1)
insert into Ingredient values (4, 'Tomate', 1)
insert into Ingredient values (5, 'Salade', 1)
insert into Ingredient values (6, 'Poivron', 1)
insert into Ingredient values (7, 'Champignon', 1)
insert into Ingredient values (8, 'Chou rouge', 1)
insert into Ingredient values (9, 'Maïs', 1)
insert into Ingredient values (10, 'Coleslaw', 1)
insert into Ingredient values (11, 'Poulet frit', 0)
insert into Ingredient values (12, 'Blanc de poulet', 0)
insert into Ingredient values (13, 'Cuisse de poulet', 0)
insert into Ingredient values (14, 'Aile de poulet', 0)
insert into Ingredient values (15, 'Lardons', 0)
insert into Ingredient values (16, 'Jambon', 0)
insert into Ingredient values (17, 'Bacon', 0)
insert into Ingredient values (18, 'Nuggets', 0)
insert into Ingredient values (19, 'Filet de poulet', 0)
insert into Ingredient values (20, 'Fromage à raclette', 0)
insert into Ingredient values (21, 'Gruyère', 0)
insert into Ingredient values (22, 'Emmental', 0)
insert into Ingredient values (23, 'Comté', 0)
insert into Ingredient values (24, 'Mozzarella', 0)
insert into Ingredient values (25, 'Cheddar', 0)
insert into Ingredient values (26, 'Reblochon', 0)
insert into Ingredient values (27, 'Pain brioché', 0)
insert into Ingredient values (28, 'Frites', 0)
insert into Ingredient values (29, 'Crème fraîche', 0)
insert into Ingredient values (30, 'Beurre', 0)
insert into Ingredient values (31, 'Huile de friture', 0)
insert into Ingredient values (32, 'Chapelure', 0)
insert into Ingredient values (33, 'Farine', 0)
insert into Ingredient values (34, 'Œuf', 0)
