insert into Organisation values (1, 'L Ordre du Tenrac Thomas-Daniel Perret', 'Ordre', 8)
insert into Organisation values (2, 'L Ordre du Tenrac Agnès Blanchard', 'Ordre', 10)
insert into Organisation values (3, 'L Ordre du Tenrac Théophile du Roche', 'Ordre', 7)
insert into Organisation values (4, 'L Ordre du Tenrac Marie Bertin', 'Ordre', 10)
insert into Organisation values (6, 'Club Tenrac Delannoynec', 'Club', 7)
insert into Organisation values (7, 'Club Tenrac Faure', 'Club', 5)
insert into Organisation values (8, 'Club Tenrac Pasquier', 'Club', 3)
insert into Organisation values (9, 'Club Tenrac GuilletVille', 'Club', 1)
insert into Organisation values (10, 'Club Tenrac Collet', 'Club', 9)
insert into Organisation values (11, 'Club Tenrac Alves-les-Bains', 'Club', 9)
insert into Organisation values (12, 'Club Tenrac Charpentier', 'Club', 1)
insert into Organisation values (13, 'Club Tenrac Sainte Colette', 'Club', 2)
insert into Organisation values (14, 'Club Tenrac Royer-sur-Antoine', 'Club', 1)
insert into Organisation values (15, 'Club Tenrac Bouchetnec', 'Club', 2)
insert into Organisation values (16, 'Club Tenrac Peron', 'Club', 7)
insert into Organisation values (17, 'Club Tenrac Leclercboeuf', 'Club', 9)
insert into Organisation values (18, 'Club Tenrac Roy', 'Club', 3)
insert into Organisation values (19, 'Club Tenrac Dufour-les-Bains', 'Club', 9)
insert into Organisation values (20, 'Club Tenrac Hamonnec', 'Club', 5)
insert into Organisation values (21, 'Club Tenrac Petitjeanboeuf', 'Club', 2)
insert into Organisation values (22, 'Club Tenrac Moulin', 'Club', 9)
insert into Organisation values (23, 'Club Tenrac Sainte Margotboeuf', 'Club', 4)
insert into Organisation values (24, 'Club Tenrac Bouvier', 'Club', 5)
insert into Organisation values (25, 'Club Tenrac Saint Augustin', 'Club', 5)
insert into Organisation values (26, 'Club Tenrac Loiseaudan', 'Club', 2)
insert into Organisation values (27, 'Club Tenrac Sainte Virginie', 'Club', 6)
insert into Organisation values (28, 'Club Tenrac Jacob-la-Forêt', 'Club', 6)
insert into Organisation values (29, 'Club Tenrac Allaindan', 'Club', 8)
insert into Organisation values (30, 'Club Tenrac RichardVille', 'Club', 10)
insert into Organisation values (31, 'Club Tenrac Delattre', 'Club', 6)
insert into Organisation values (32, 'Club Tenrac Boucher-sur-Pereira', 'Club', 1)
insert into Organisation values (33, 'Club Tenrac Vidal', 'Club', 4)
insert into Organisation values (34, 'Club Tenrac Mullerdan', 'Club', 8)
insert into Organisation values (35, 'Club Tenrac Thomas-les-Bains', 'Club', 3)
insert into Organisation values (36, 'Club Tenrac Mace-sur-Mer', 'Club', 1)
insert into Organisation values (37, 'Club Tenrac Hamon', 'Club', 8)
insert into Organisation values (38, 'Club Tenrac Rolland-la-Forêt', 'Club', 9)
insert into Organisation values (39, 'Club Tenrac Léger-sur-Tessier', 'Club', 1)
insert into Organisation values (40, 'Club Tenrac Saint ÉmilieBourg', 'Club', 4)
insert into Organisation values (41, 'Club Tenrac Regnierdan', 'Club', 5)
insert into Organisation values (42, 'Club Tenrac Devauxdan', 'Club', 3)
insert into Organisation values (43, 'Club Tenrac Grondin', 'Club', 8)
insert into Organisation values (44, 'Club Tenrac Rey', 'Club', 7)
insert into Organisation values (45, 'Club Tenrac Sanchez-sur-Mer', 'Club', 3)
insert into Organisation values (46, 'Club Tenrac BergerVille', 'Club', 5)
insert into Organisation values (47, 'Club Tenrac Lambert', 'Club', 1)
insert into Organisation values (48, 'Club Tenrac Hardy', 'Club', 6)
insert into Organisation values (49, 'Club Tenrac Sainte Mauricenec', 'Club', 8)
insert into Organisation values (50, 'Club Tenrac Saint Marine', 'Club', 2)
insert into Organisation values (51, 'Club Tenrac Gautier', 'Club', 6)
insert into Organisation values (52, 'Club Tenrac Pierre', 'Club', 10)
insert into Organisation values (53, 'Club Tenrac Fabredan', 'Club', 1)
insert into Organisation values (54, 'Club Tenrac Sainte WilliamVille', 'Club', 3)
insert into Organisation values (55, 'Club Tenrac Saint Patricknec', 'Club', 9)
insert into Organisation values (56, 'Club Tenrac Lemaître-sur-Mer', 'Club', 3)
insert into Organisation values (57, 'Club Tenrac De Oliveira', 'Club', 8)
insert into Organisation values (58, 'Club Tenrac Andre-sur-Mercier', 'Club', 9)
insert into Organisation values (59, 'Club Tenrac ValletVille', 'Club', 5)
insert into Organisation values (60, 'Club Tenrac Potier', 'Club', 8)
insert into Organisation values (61, 'Club Tenrac Lagarde', 'Club', 6)
insert into Organisation values (62, 'Club Tenrac Sainte AgnèsVille', 'Club', 10)
insert into Organisation values (63, 'Club Tenrac Delannoy', 'Club', 10)
insert into Organisation values (64, 'Club Tenrac Maillard', 'Club', 7)
insert into Organisation values (65, 'Club Tenrac Samson', 'Club', 3)
insert into Organisation values (66, 'Club Tenrac Buisson', 'Club', 5)
insert into Organisation values (67, 'Club Tenrac Sainte AdrienneBourg', 'Club', 2)
insert into Organisation values (68, 'Club Tenrac Laurentboeuf', 'Club', 2)
insert into Organisation values (69, 'Club Tenrac Alexandre', 'Club', 6)
insert into Organisation values (70, 'Club Tenrac Sainte Audrey', 'Club', 9)
insert into Organisation values (71, 'Club Tenrac Le Roux', 'Club', 8)
insert into Organisation values (72, 'Club Tenrac Jacob', 'Club', 2)
insert into Organisation values (73, 'Club Tenrac Valentin', 'Club', 7)
insert into Organisation values (74, 'Club Tenrac Sainte Margueritedan', 'Club', 3)
insert into Organisation values (75, 'Club Tenrac Sainte Luce', 'Club', 3)
insert into Organisation values (76, 'Club Tenrac MarchalBourg', 'Club', 5)
insert into Organisation values (77, 'Club Tenrac Leroy', 'Club', 8)
insert into Organisation values (78, 'Club Tenrac Saint Odetteboeuf', 'Club', 7)
insert into Organisation values (79, 'Club Tenrac Navarro', 'Club', 5)
insert into Organisation values (80, 'Club Tenrac Leroy-sur-Fabre', 'Club', 10)
insert into Organisation values (81, 'Club Tenrac Saint OlivierBourg', 'Club', 4)
insert into Organisation values (82, 'Club Tenrac Arnaud', 'Club', 7)
insert into Organisation values (83, 'Club Tenrac Fleury', 'Club', 2)
insert into Organisation values (84, 'Club Tenrac Julien', 'Club', 8)
insert into Organisation values (85, 'Club Tenrac Leroy-la-Forêt', 'Club', 1)
insert into Organisation values (86, 'Club Tenrac Antoinedan', 'Club', 7)
insert into Organisation values (87, 'Club Tenrac Poirier', 'Club', 1)
insert into Organisation values (88, 'Club Tenrac Saint Benjamin', 'Club', 9)
insert into Organisation values (89, 'Club Tenrac Marchal', 'Club', 6)
insert into Organisation values (90, 'Club Tenrac De Sousa', 'Club', 5)
insert into Organisation values (91, 'Club Tenrac Saint Charlesboeuf', 'Club', 2)
insert into Organisation values (92, 'Club Tenrac Peltierboeuf', 'Club', 5)
insert into Organisation values (93, 'Club Tenrac Guilbert-les-Bains', 'Club', 2)
insert into Organisation values (94, 'Club Tenrac Raymond', 'Club', 3)
insert into Organisation values (95, 'Club Tenrac Chevallier', 'Club', 2)
insert into Organisation values (96, 'Club Tenrac Guilbertboeuf', 'Club', 1)
insert into Organisation values (97, 'Club Tenrac Guillaume', 'Club', 5)
insert into Organisation values (98, 'Club Tenrac Ramosboeuf', 'Club', 7)
insert into Organisation values (99, 'Club Tenrac Mahe-la-Forêt', 'Club', 10)
insert into Organisation values (100, 'Club Tenrac Pinto', 'Club', 10)
insert into Organisation values (101, 'Club Tenrac Saint Guillaume-la-Forêt', 'Club', 9)
insert into Organisation values (102, 'Club Tenrac Couturier-la-Forêt', 'Club', 5)
insert into Organisation values (103, 'Club Tenrac Gomes', 'Club', 5)
insert into Organisation values (104, 'Club Tenrac Imbertdan', 'Club', 4)
insert into Organisation values (105, 'Club Tenrac Gros', 'Club', 7)
insert into Organisation values (106, 'Club Tenrac Gautier', 'Club', 4)
insert into Organisation values (107, 'Club Tenrac Saint Léon', 'Club', 10)
insert into Organisation values (108, 'Club Tenrac Dupuy', 'Club', 10)
insert into Organisation values (109, 'Club Tenrac Renault', 'Club', 7)
insert into Organisation values (110, 'Club Tenrac Sainte Franck-sur-Mer', 'Club', 10)
insert into Organisation values (111, 'Club Tenrac Lebrun-sur-Mer', 'Club', 2)
insert into Organisation values (112, 'Club Tenrac ImbertVille', 'Club', 2)
insert into Organisation values (113, 'Club Tenrac Maury-sur-Hamel', 'Club', 7)
insert into Organisation values (114, 'Club Tenrac Hamel', 'Club', 10)
insert into Organisation values (115, 'Club Tenrac LaporteBourg', 'Club', 5)
insert into Organisation values (116, 'Club Tenrac Riou-sur-Mer', 'Club', 7)
insert into Organisation values (117, 'Club Tenrac Fournier', 'Club', 7)
insert into Organisation values (118, 'Club Tenrac Bazin', 'Club', 2)
insert into Organisation values (119, 'Club Tenrac Le GoffBourg', 'Club', 8)
insert into Organisation values (120, 'Club Tenrac Martel', 'Club', 7)
insert into Organisation values (121, 'Club Tenrac ThibaultVille', 'Club', 8)
insert into Organisation values (122, 'Club Tenrac Fontaine-sur-Bonnet', 'Club', 2)
insert into Organisation values (123, 'Club Tenrac CollinVille', 'Club', 8)
insert into Organisation values (124, 'Club Tenrac Sainte Célina', 'Club', 9)
insert into Organisation values (125, 'Club Tenrac De Sousa', 'Club', 7)
insert into Organisation values (126, 'Club Tenrac Bouvier', 'Club', 6)
insert into Organisation values (127, 'Club Tenrac PeltierBourg', 'Club', 10)
insert into Organisation values (128, 'Club Tenrac Huet-sur-Mer', 'Club', 3)
insert into Organisation values (129, 'Club Tenrac Tessier', 'Club', 2)
insert into Organisation values (130, 'Club Tenrac Merle', 'Club', 9)
insert into Organisation values (131, 'Club Tenrac Seguin', 'Club', 6)
insert into Organisation values (132, 'Club Tenrac Masse', 'Club', 10)
insert into Organisation values (133, 'Club Tenrac AugerVille', 'Club', 3)
insert into Organisation values (134, 'Club Tenrac Lebrun', 'Club', 3)
insert into Organisation values (135, 'Club Tenrac Noël', 'Club', 2)
insert into Organisation values (136, 'Club Tenrac Camus', 'Club', 9)
insert into Organisation values (137, 'Club Tenrac Sainte Nath-la-Forêt', 'Club', 7)
insert into Organisation values (138, 'Club Tenrac Bouvier', 'Club', 4)
insert into Organisation values (139, 'Club Tenrac Perez', 'Club', 5)
insert into Organisation values (140, 'Club Tenrac Besson-sur-Mer', 'Club', 10)
insert into Organisation values (141, 'Club Tenrac Perret-les-Bains', 'Club', 6)
insert into Organisation values (142, 'Club Tenrac Leblanc', 'Club', 10)
insert into Organisation values (143, 'Club Tenrac Sainte PhilippineVille', 'Club', 10)
insert into Organisation values (144, 'Club Tenrac Pascal-la-Forêt', 'Club', 8)
insert into Organisation values (145, 'Club Tenrac Saint Raymondnec', 'Club', 5)
insert into Organisation values (146, 'Club Tenrac Fouquet', 'Club', 1)
insert into Organisation values (147, 'Club Tenrac Voisin-sur-Mer', 'Club', 2)
insert into Organisation values (148, 'Club Tenrac Diaz', 'Club', 2)
insert into Organisation values (149, 'Club Tenrac Adamnec', 'Club', 3)
insert into Organisation values (150, 'Club Tenrac Saint Emmanuellenec', 'Club', 9)
insert into Organisation values (151, 'Club Tenrac Laporte-sur-Mer', 'Club', 4)
insert into Organisation values (152, 'Club Tenrac Dupré', 'Club', 10)
insert into Organisation values (153, 'Club Tenrac Buisson-sur-Mer', 'Club', 10)
insert into Organisation values (154, 'Club Tenrac Sainte ThibautVille', 'Club', 8)
insert into Organisation values (155, 'Club Tenrac Sainte Juliette', 'Club', 4)
insert into Organisation values (156, 'Club Tenrac Morin', 'Club', 5)
insert into Organisation values (157, 'Club Tenrac Ruiz-sur-Bourdon', 'Club', 9)
insert into Organisation values (158, 'Club Tenrac Sainte Grégoire', 'Club', 9)
insert into Organisation values (159, 'Club Tenrac Saint François', 'Club', 1)
insert into Organisation values (160, 'Club Tenrac Guyotnec', 'Club', 10)
insert into Organisation values (161, 'Club Tenrac Sainte Odetteboeuf', 'Club', 5)
insert into Organisation values (162, 'Club Tenrac Sainte Corinne-la-Forêt', 'Club', 4)
insert into Organisation values (163, 'Club Tenrac Bègue-sur-Fontaine', 'Club', 4)
insert into Organisation values (164, 'Club Tenrac BerthelotBourg', 'Club', 7)
insert into Organisation values (165, 'Club Tenrac Olivierboeuf', 'Club', 6)
insert into Organisation values (166, 'Club Tenrac Saint Rogerdan', 'Club', 2)
insert into Organisation values (167, 'Club Tenrac Saint Charlotte', 'Club', 8)
insert into Organisation values (168, 'Club Tenrac Pereira-la-Forêt', 'Club', 10)
insert into Organisation values (169, 'Club Tenrac Dos Santos', 'Club', 7)
insert into Organisation values (170, 'Club Tenrac Marchand', 'Club', 6)
insert into Organisation values (171, 'Club Tenrac Guillot', 'Club', 4)
insert into Organisation values (172, 'Club Tenrac Normand', 'Club', 7)
insert into Organisation values (173, 'Club Tenrac Caron-sur-Mer', 'Club', 1)
insert into Organisation values (174, 'Club Tenrac Lecomte', 'Club', 8)
insert into Organisation values (175, 'Club Tenrac Dias-les-Bains', 'Club', 10)
insert into Organisation values (176, 'Club Tenrac Descamps-sur-Mer', 'Club', 5)
insert into Organisation values (177, 'Club Tenrac Pinto-sur-Jacques', 'Club', 1)
insert into Organisation values (178, 'Club Tenrac Descamps-sur-Mer', 'Club', 9)
insert into Organisation values (179, 'Club Tenrac Foucherdan', 'Club', 10)
insert into Organisation values (180, 'Club Tenrac Meunier', 'Club', 3)
insert into Organisation values (181, 'Club Tenrac Payet', 'Club', 6)
insert into Organisation values (182, 'Club Tenrac Gérard', 'Club', 2)
insert into Organisation values (183, 'Club Tenrac Le GallBourg', 'Club', 2)
insert into Organisation values (184, 'Club Tenrac Lenoir-la-Forêt', 'Club', 7)
insert into Organisation values (185, 'Club Tenrac Morvan', 'Club', 3)
insert into Organisation values (186, 'Club Tenrac Lebreton', 'Club', 4)
insert into Organisation values (187, 'Club Tenrac Sainte Alexandrie', 'Club', 3)
insert into Organisation values (188, 'Club Tenrac Saint ChristopheVille', 'Club', 6)
insert into Organisation values (189, 'Club Tenrac Monnier', 'Club', 9)
insert into Organisation values (190, 'Club Tenrac De Sousa', 'Club', 7)
insert into Organisation values (191, 'Club Tenrac Lebonboeuf', 'Club', 7)
insert into Organisation values (192, 'Club Tenrac Guérinboeuf', 'Club', 8)
insert into Organisation values (193, 'Club Tenrac Saint Adrien', 'Club', 9)
insert into Organisation values (194, 'Club Tenrac Tessierboeuf', 'Club', 2)
insert into Organisation values (195, 'Club Tenrac Faure', 'Club', 3)
insert into Organisation values (196, 'Club Tenrac Saint Daniellenec', 'Club', 9)
insert into Organisation values (197, 'Club Tenrac Torres', 'Club', 10)
insert into Organisation values (198, 'Club Tenrac Rodriguez-les-Bains', 'Club', 10)
insert into Organisation values (199, 'Club Tenrac Barre', 'Club', 4)
insert into Organisation values (200, 'Club Tenrac Sainte Pauline', 'Club', 6)
