insert into Plat values ('French fries with sausages')
insert into Plat values ('Linguine with clams')
insert into Plat values ('Teriyaki Chicken donburi')
insert into Plat values ('Philadelphia maki')
insert into Plat values ('California maki')
insert into Plat values ('Mushroom Risotto')
insert into Plat values ('Pork sausage roll')
insert into Plat values ('Fettuccine Alfredo')
insert into Plat values ('Risotto with seafood')
insert into Plat values ('Vegetable Soup')
insert into Plat values ('Tiramisù')
insert into Plat values ('Cheeseburger')
insert into Plat values ('Tuna sashimi')
insert into Plat values ('Chilli con carne')
insert into Plat values ('Pasta and Beans')
insert into Plat values ('Fish and chips')
insert into Plat values ('Lasagne')
insert into Plat values ('Pasta with Tomato and Basil')
insert into Plat values ('Souvlaki')
insert into Plat values ('Chicken milanese')
insert into Plat values ('Salmon nigiri')
insert into Plat values ('Caesar Salad')
insert into Plat values ('Chicken Fajitas')
insert into Plat values ('Pork belly buns')
insert into Plat values ('Ricotta stuffed Ravioli')
insert into Plat values ('Caprese Salad')
insert into Plat values ('Ebiten maki')
insert into Plat values ('Barbecue Ribs')
insert into Plat values ('Scotch eggs')
insert into Plat values ('Katsu Curry')
insert into Plat values ('Pasta Carbonara')
insert into Plat values ('Bruschette with Tomato')
insert into Plat values ('Pappardelle alla Bolognese')
insert into Plat values ('Califlower penne')
insert into Plat values ('Pizza')
insert into Plat values ('Meatballs with sauce')
insert into Plat values ('Chicken wings')
