insert into Territoire values (1, 'Guyane')
insert into Territoire values (2, 'Province-Alpes-Côte d Azur')
insert into Territoire values (3, 'Centre')
insert into Territoire values (4, 'Wallis-et-Futuna')
insert into Territoire values (5, 'Rhone-Alpes')
insert into Territoire values (6, 'Guadeloupe')
insert into Territoire values (7, 'Province-Alpes-Côte d Azur')
insert into Territoire values (8, 'Bourgogne')
insert into Territoire values (9, 'Bourgogne')
insert into Territoire values (10, 'Guadeloupe')
